### ISSUE TITLE
git-lfs 1.3.1 resolving git server short hostname incorrectly

### ISSUE THREAD

**Issue by jamesblackburn** [git-lfs/git-lfs#1464]
## Summary

Using the latest `git-lfs` 1.3.1 release against an Atlassian Bitbucket server, I see that LFS fails to resolve the short hostname.  Instead of using the `shorthost` it attempts to use `www.shorthost.com`.

The below works with `git-lfs` 1.1.2 from homebrew.
## Logs

LFS fails like this:

```
LONMQR1QU:tmp jblackburn$ git clone ssh://git@ahlgit.maninvestments.com:7999/core/ahl.core.git
Cloning into 'ahl.core'...
remote: Counting objects: 92559, done.
remote: Compressing objects: 100% (32494/32494), done.
remote: Total 92559 (delta 62052), reused 89281 (delta 59143)
Receiving objects: 100% (92559/92559), 12.80 MiB | 14.73 MiB/s, done.
Resolving deltas: 100% (62052/62052), done.
Checking connectivity... done.
Downloading ahl/visualization/interactive/examples/examples.ipynb (212.67 KB)
Error downloading object: ahl/visualization/interactive/examples/examples.ipynb (9ad3d0dc17b84c0da9577d50ffcd8eda89327219e449dbe28523180b0de894ed)

Errors logged to /Users/jblackburn/git/tmp/ahl.core/.git/lfs/objects/logs/20160818T180418.505861052.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge %f failed 2
error: external filter git-lfs smudge %f failed
fatal: ahl/visualization/interactive/examples/examples.ipynb: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

The logfile shows:

```
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)
git version 2.9.2

$ git-lfs smudge ahl/visualization/interactive/examples/examples.ipynb
Error downloading object: ahl/visualization/interactive/examples/examples.ipynb (9ad3d0dc17b84c0da9577d50ffcd8eda89327219e449dbe28523180b0de894ed)

Server error: http://www.ahlgit.com/scm/core/ahl.core.git/info/lfs/objects/batch from HTTP 503
goroutine 1 [running]:
github.com/github/git-lfs/errutil.Stack(0x0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:579 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x973270, 0xc82024c028, 0x9af6a8, 0xc8201f45d0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:223 +0xf80
github.com/github/git-lfs/commands.logPanic(0x9af6a8, 0xc8201f45d0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:187 +0x412
github.com/github/git-lfs/commands.handlePanic(0x9af6a8, 0xc8201f45d0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:162 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x9af6a8, 0xc8201f45d0, 0x601420, 0x21, 0xc82018dc98, 0x2, 0x2)
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:97 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0x82d100, 0xc820011c70, 0x1, 0x1)
        /Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:79 +0xdc6
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0x82d100, 0xc820011bc0, 0x1, 0x1, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x3f4
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0x82e2e0, 0x0, 0x0)
        /Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
        /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:112 +0x23
main.main()
        /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:33 +0x12e
```

It looks like instead of using `ahlgit` as a shorthost, `git-lfs` is expanding that to `www.ahlgit.com`

Any thoughts?

Cheers,
James

**Comment by technoweenie** [comment]
What does `git config --list` show? Also, what is bitbucket returning for the following command?

```
$ ssh git@ahlgit.maninvestments.com git-lfs-authenticate core/ahl.core download
```

**Comment by jamesblackburn** [comment]
```
LONMQR1QU:tmp jblackburn$ git lfs version
git-lfs/1.3.1 (GitHub; darwin amd64; go 1.6.3; git 9c9dffb)
LONMQR1QU:tmp jblackburn$ git config --list
core.excludesfile=~/.gitignore
core.legacyheaders=false
core.quotepath=false
core.pager=less
mergetool.keepbackup=true
push.default=simple
color.ui=auto
color.interactive=auto
repack.usedeltabaseoffset=true
alias.s=status
alias.a=!git add . && git status
alias.au=!git add -u . && git status
alias.aa=!git add . && git add -u . && git status
alias.c=commit
alias.cm=commit -m
alias.ca=commit --amend
alias.ac=!git add . && git commit
alias.acm=!git add . && git commit -m
alias.l=log --graph --all --pretty=format:'%C(yellow)%h%C(cyan)%d%Creset %s %C(white)- %an, %ar%Creset'
alias.ll=log --stat --abbrev-commit
alias.lg=log --color --graph --pretty=format:'%C(bold white)%h%Creset -%C(bold green)%d%Creset %s %C(bold green)(%cr)%Creset %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative
alias.llg=log --color --graph --pretty=format:'%C(bold white)%H %d%Creset%n%s%n%+b%C(bold blue)%an <%ae>%Creset %C(bold green)%cr (%ci)' --abbrev-commit
alias.d=diff
alias.master=checkout master
alias.spull=svn rebase
alias.spush=svn dcommit
alias.alias=!git config --list | grep 'alias\.' | sed 's/alias\.\([^=]*\)=\(.*\)/\1\	 => \2/' | sort
include.path=~/.gitcinclude
include.path=.githubconfig
include.path=.gitcredential
diff.exif.textconv=exif
credential.helper=osxkeychain
filter.lfs.clean=git-lfs clean %f
filter.lfs.smudge=git-lfs smudge %f
filter.lfs.required=true
http.proxy=http://euro-webproxy.drama.man.com:8080
user.name=James Blackburn
user.email=jblackburn@ahl.com
pull.rebase=true
push.default=simple
rebase.autostash=true
```

The second command doesn't auth. The git server has my SSH key, but using normal SSH doesn't seem to work -- perhaps I'm doing something wrong?  

```
LONMQR1QU:tmp jblackburn$ ssh git@ahlgit.maninvestments.com git-lfs-authenticate core/ahl.core download

This system is restricted to authorised users for legitimate business purposes.
Usage is recorded and subject to audit.  The actual or attempted unauthorised
access, use of or modification of computer systems is a violation of the UK
Computer Misuse Act (1990).  You will have been informed if you are authorised
to use this system.  If so, proceed: otherwise exit this system immediately.

git@ahlgit.maninvestments.com's password:
```

I can get on to the server, but afaics there's no git-lfs or git-lfs-authenticate on there.

```
[jblackburn~]$ git-l<tab><tab>
git-log        git-ls-files   git-ls-remote  git-ls-tree
```

**Comment by jamesblackburn** [comment]
Argh. I see I have:

```
[http]
	proxy = http://euro-webproxy.drama.man.com:8080
```

In my `~/.gitconfig`. I guess the previous version didn't support that? If I comment this out, the lfs clone works.

Ideally it wouldn't be attempting to hit the proxy for local hosts...  
```
LONMQR1QU:tmp jblackburn$ ping ahlgit
PING plonapahls86.maninvestments.com (10.192.128.108): 56 data bytes
64 bytes from 10.192.128.108: icmp_seq=0 ttl=54 time=2.362 ms
```

Given `git` can clone this repo, shouldn't git-lfs be able to also fetch large files from it?

**Comment by ttaylorr** [comment]
Hi @jamesblackburn, is this still an issue with the latest version of Git LFS? I'm inclined to believe that it is not, since I can't remember any other bug reports based on this since the original one that you opened that I am commenting on now.

Since the issue has been quiet for a little under two years, I am going to close it for now. But, if things aren't still working, please do let me know here and I will begin looking into it again. Thanks!
