### ISSUE TITLE
git-lfs installed errors on macOS 10.12

### ISSUE THREAD

**Issue by SongHuaixu** [git-lfs/git-lfs#1662]
```
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Installing dependencies for git-lfs: go
==> Installing git-lfs dependency: go
==> Downloading https://storage.googleapis.com/golang/go1.6.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/go-1.6.tar.gz
==> Downloading https://storage.googleapis.com/golang/go1.4.2.darwin-amd64-osx10
Already downloaded: /Library/Caches/Homebrew/go--gobootstrap-10.8.tar.gz
==> ./make.bash --no-clean
Last 15 lines from /Users/songhuaixu/Library/Logs/Homebrew/go/01.make.bash:
	/usr/local/go/src/syscall/syscall_unix.go:136 +0x58
os.(*File).read(0xc2082761d0, 0xc208259800, 0x200, 0x200, 0xc208259800, 0x0, 0x0)
	/usr/local/go/src/os/file_unix.go:191 +0x86
os.(*File).Read(0xc2082761d0, 0xc208259800, 0x200, 0x200, 0x1, 0x0, 0x0)
	/usr/local/go/src/os/file.go:95 +0x91
bytes.(*Buffer).ReadFrom(0xc20844d490, 0x46e300, 0xc2082761d0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:169 +0x25a
io.Copy(0x47a290, 0xc20844d490, 0x46e300, 0xc2082761d0, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:358 +0x13d
os/exec.func·003(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:221 +0x7d
os/exec.func·004(0xc2081079c0)
	/usr/local/go/src/os/exec/exec.go:328 +0x2d
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:329 +0xb6d

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
Validation Failed
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:523:in `open'
	from /usr/local/Library/Homebrew/utils.rb:554:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:586:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:222:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:218:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:263:in `dump'
	from /usr/local/Library/brew.rb:132:in `rescue in <main>'
	from /usr/local/Library/brew.rb:28:in `<main>'
```

**Comment by technoweenie** [comment]
That seems to be a homebrew issue installing Go. Have you tried following the directions at https://git.io/brew-troubleshooting?

Also, you can install git lfs without compiling anything by downloading the "Mac AMD64" build of [git lfs v1.4.4](https://github.com/git-lfs/git-lfs/releases/tag/v1.4.4). Just put the `git-lfs` binary in your `$PATH` somewhere.

**Comment by SongHuaixu** [comment]
Thank you. It was a success.
