### ISSUE TITLE
Problem with symlinks (junctions) in Windows

### ISSUE THREAD

**Issue by gregerc** [git-lfs/git-lfs#1718]
In windows cmd, if I access a repository while standing in a symlinked directory, git lfs crashes:

<pre>
user@computer C:\Users\user\Projects\myProject
> git lfs env
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x7a6aa0, 0xc04200c090)
        C:/Go/src/runtime/panic.go:500 +0x1af
path/filepath.walkLinks(0xc042118090, 0x19, 0xc042099980, 0x1a, 0xc042118090, 0x0, 0x40f318)
        C:/Go/src/path/filepath/symlink.go:84 +0x4cf
path/filepath.walkLinks(0xc042118090, 0x1a, 0xc042099980, 0x1a, 0xc0421180aa, 0x9, 0xc042118090)
        C:/Go/src/path/filepath/symlink.go:68 +0x102
path/filepath.walkLinks(0xc042118090, 0x23, 0xc042099980, 0x24, 0xc042118090, 0x0, 0x2b)
        C:/Go/src/path/filepath/symlink.go:73 +0x28f
path/filepath.walkLinks(0xc042118090, 0x24, 0xc042099980, 0x24, 0xc0421180b4, 0x4, 0x64)
        C:/Go/src/path/filepath/symlink.go:68 +0x102
path/filepath.walkLinks(0xc042118090, 0x28, 0xc042099980, 0xc042118030, 0x4, 0xc042118090, 0x28)
        C:/Go/src/path/filepath/symlink.go:73 +0x28f
path/filepath.walkSymlinks(0xc042118090, 0x28, 0x0, 0xc04207f080, 0xc0420ea540, 0xc0420c9f01)
        C:/Go/src/path/filepath/symlink.go:98 +0x70
path/filepath.evalSymlinks(0xc042118090, 0x28, 0xc0420f00d0, 0xc042099af0, 0x5b674e, 0x7a2c80)
        C:/Go/src/path/filepath/symlink_windows.go:110 +0x40
path/filepath.EvalSymlinks(0xc042118090, 0x28, 0x808ed0, 0x9, 0x80b673, 0xf)
        C:/Go/src/path/filepath/path.go:227 +0x3c
github.com/git-lfs/git-lfs/tools.ResolveSymlinks(0xc042118090, 0x28, 0xc042118035, 0x23)
        C:/Go/src/github.com/git-lfs/git-lfs/tools/filetools.go:62 +0x45
github.com/git-lfs/git-lfs/config.ResolveGitBasicDirs()
        C:/Go/src/github.com/git-lfs/git-lfs/config/filesystem.go:30 +0x294
github.com/git-lfs/git-lfs/localstorage.ResolveDirs()
        C:/Go/src/github.com/git-lfs/git-lfs/localstorage/currentstore.go:31 +0x3e
github.com/git-lfs/git-lfs/commands.resolveLocalStorage(0xc0420e6000, 0x9ff348, 0x0, 0x0)
        C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:78 +0x1b
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc0420e6000, 0x9ff348, 0x0, 0x0, 0xc0420e6000, 0x9ff348)
        C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:474 +0x25c
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0420716c0, 0xc042099eb0, 0x1)
        C:/Go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x364
github.com/git-lfs/git-lfs/commands.Run()
        C:/Go/src/github.com/git-lfs/git-lfs/commands/run.go:65 +0x19d
main.main()
        C:/Go/src/github.com/git-lfs/git-lfs/git-lfs.go:33 +0x118
</pre>

Here `C:\Users\user\Projects` is symlinked to `C:\Projects`.

**Comment by technoweenie** [comment]
Thanks for the report, should be easy to replicate in a test, and fix for the next v1.5.x release.

**Comment by technoweenie** [comment]
Can you show me `git lfs version` output so I can confirm what Go version is used? This will help match up the line numbers to internal go code.

If you don't reply, I'll assume you're using one of our official builds, which was compiled with Go 1.7.3 :)

**Comment by technoweenie** [comment]
I'm not able to replicate this on my windows VM:

```bash
techn@DESKTOP-RI7AHME MINGW64 ~/go/src/github.com/git-lfs/git-lfs (windows-symlink-fix)
$ test/test-env.sh
compile git-lfs for test/test-env.sh
commands\mancontent_gen.go
Using go1.7.3
Git LFS: /c/Users/techn/go/src/github.com/git-lfs/git-lfs/bin/git-lfs
git-lfs/1.5.0 (GitHub; windows amd64; go 1.7.3; git 42e6d8c)
git version 2.10.2.windows.1
Updated pre-push hook.
Git LFS initialized.

HOME: /c/Users/techn/go/src/github.com/git-lfs/git-lfs/test/remote/home
TMP: /tmp/git-lfs_TEMP.WJY3RG
CREDS: /c/Users/techn/go/src/github.com/git-lfs/git-lfs/test/remote/creds
lfstest-gitserver:
  LFSTEST_URL=/c/Users/techn/go/src/github.com/git-lfs/git-lfs/test/remote/url
  LFSTEST_SSL_URL=/c/Users/techn/go/src/github.com/git-lfs/git-lfs/test/remote/sslurl
  LFSTEST_CERT=/c/Users/techn/go/src/github.com/git-lfs/git-lfs/test/remote/cert
  LFSTEST_DIR=/c/Users/techn/go/src/github.com/git-lfs/git-lfs/test/remote
GIT:
filter.lfs.clean git-lfs clean -- %f
filter.lfs.smudge git-lfs smudge -- %f
filter.lfs.process git-lfs filter-process
filter.lfs.required true
credential.usehttppath true
credential.helper lfstest
user.name Git LFS Tests
user.email git-lfs@example.com

test: env with no remote ...                                       OK
test: env with origin remote ...                                   OK
test: env with multiple remotes ...                                OK
test: env with other remote ...                                    OK
test: env with multiple remotes and lfs.url config ...             OK
test: env with multiple remotes and lfs configs ...                OK
test: env with multiple remotes and lfs url and batch configs ...  OK
test: env with .lfsconfig ...                                      OK
test: env with environment variables ...                           OK
test: env with bare repo ...                                       OK
test: env with multiple ssh remotes ...                            OK
test: env with skip download errors ...                            OK
test: env with extra transfer methods ...                          OK
test: env in symlink ...                                           FAILED
-- stdout --
    Initialized empty Git repository in C:/Users/techn/AppData/Local/Temp/git-lfs_TEMP.WJY3RG/test-env.sh-4012/projects/foo/.git/
    git-lfs/1.5.0 (GitHub; windows amd64; go 1.7.3; git 42e6d8c)
    git version 2.10.2.windows.1

    LocalWorkingDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\symlink-projects\foo
    LocalGitDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\symlink-projects\foo\.git
    LocalGitStorageDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\symlink-projects\foo\.git
    LocalMediaDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\symlink-projects\foo\.git\lfs\objects
    LocalReferenceDir=
    TempDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\symlink-projects\foo\.git\lfs\tmp
    ConcurrentTransfers=3
    TusTransfers=false
    BasicTransfersOnly=false
    BatchTransfer=true
    SkipDownloadErrors=false
    FetchRecentAlways=false
    FetchRecentRefsDays=7
    FetchRecentCommitsDays=0
    FetchRecentRefsIncludeRemotes=true
    PruneOffsetDays=3
    PruneVerifyRemoteAlways=false
    PruneRemoteName=origin
    AccessDownload=none
    AccessUpload=none
    DownloadTransfers=basic
    UploadTransfers=basic
    GIT_CONFIG_NOSYSTEM=1
    GIT_LFS_PATH=C:\Program Files\Git LFS
    git config filter.lfs.process = "git-lfs filter-process"
    git config filter.lfs.smudge = "git-lfs smudge -- %f"
    git config filter.lfs.clean = "git-lfs clean -- %f"
    current directory:
    /tmp/git-lfs_TEMP.WJY3RG/test-env.sh-4012/symlink-projects/foo
-- stderr --
    + set -e
    + mkdir -p projects/foo
    + cd projects/foo
    + git init
    + cd ../..
    + target=/tmp/git-lfs_TEMP.WJY3RG/test-env.sh-4012/projects
    + link=symlink-projects
    + ln -s /tmp/git-lfs_TEMP.WJY3RG/test-env.sh-4012/projects symlink-projects
    + cd symlink-projects/foo
    + git lfs env
    + echo 'current directory:'
    + pwd
    + exit 1
    + test_status=1

test: env in windows junction ...                                  FAILED
-- stdout --
    Initialized empty Git repository in C:/Users/techn/AppData/Local/Temp/git-lfs_TEMP.WJY3RG/test-env.sh-4012/windows-projects/foo/.git/
    git-lfs/1.5.0 (GitHub; windows amd64; go 1.7.3; git 42e6d8c)
    git version 2.10.2.windows.1

    LocalWorkingDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\windows-projects\foo
    LocalGitDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\windows-projects\foo\.git
    LocalGitStorageDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\windows-projects\foo\.git
    LocalMediaDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\windows-projects\foo\.git\lfs\objects
    LocalReferenceDir=
    TempDir=C:\Users\techn\AppData\Local\Temp\git-lfs_TEMP.WJY3RG\test-env.sh-4012\windows-projects\foo\.git\lfs\tmp
    ConcurrentTransfers=3
    TusTransfers=false
    BasicTransfersOnly=false
    BatchTransfer=true
    SkipDownloadErrors=false
    FetchRecentAlways=false
    FetchRecentRefsDays=7
    FetchRecentCommitsDays=0
    FetchRecentRefsIncludeRemotes=true
    PruneOffsetDays=3
    PruneVerifyRemoteAlways=false
    PruneRemoteName=origin
    AccessDownload=none
    AccessUpload=none
    DownloadTransfers=basic
    UploadTransfers=basic
    GIT_CONFIG_NOSYSTEM=1
    GIT_LFS_PATH=C:\Program Files\Git LFS
    git config filter.lfs.process = "git-lfs filter-process"
    git config filter.lfs.smudge = "git-lfs smudge -- %f"
    git config filter.lfs.clean = "git-lfs clean -- %f"
    current directory:
    /tmp/git-lfs_TEMP.WJY3RG/test-env.sh-4012/windows-symlink-projects/foo
-- stderr --
    + set -e
    + [[ ! -n C:\Windows ]]
    + mkdir -p windows-projects/foo
    + cd windows-projects/foo
    + git init
    + cd ../..
    + target=/tmp/git-lfs_TEMP.WJY3RG/test-env.sh-4012/windows-projects
    + link=windows-symlink-projects
    + cmd
    + cd windows-symlink-projects/foo
    + git lfs env
    + echo 'current directory:'
    + pwd
    + exit 1
    + test_status=1
```

Based on that stack trace, this seems to be a problem with Go itself. It looks like it's been reported and fixed already too: golang/go#15978. When Go 1.8 comes out, we'll make a new Git LFS release that includes the fix.

**Comment by gregerc** [comment]
My version:
<pre>
> git lfs version
git-lfs/1.5.2 (GitHub; windows amd64; go 1.7.3; git 547a06aa)
</pre>
What if you create the links with the windows command `mklink /d <source> <destination>`?

**Comment by technoweenie** [comment]
That should be happening [here](https://github.com/git-lfs/git-lfs/blob/42e6d8c396026ca5534afac31d87f299f8956d97/test/test-env.sh#L881).

As luck would have it, the Go team published a go1.8beta1 build. Would you mind [downloading this LFS build](https://github.com/git-lfs/git-lfs/releases/tag/v1.5.2-go1.8beta1) and trying it? You don't have to install it anywhere special, you can run it from your Downloads directory.

```bash
$ cd C:\Users\user\Projects\myProject
$ C:\Users\user\Downloads\git-lfs-windows-amd64-1.5.2\git-lfs env
```

Looks like there's a minor LFS test failure with Go1.8 that we need to investigate, so I wouldn't use this beta build for general LFS work. I just want to see if the fix for golang/go#15978 solves your problem.

Also, what shell in windows are you using?

* Windows cmd?
* Cygwin?
* Git Bash (from Git for Windows)
* Git cmd (from Git for Windows)
* Some Git shell from SourceTree or GitHub Desktop?

**Comment by gregerc** [comment]
Sorry for taking a while, got busy at work. The version compiled with 1.8beta1 (git 547a06a) works, thanks!

I use git, git lfs from within Git Extensions (the GUI), Windows cmd, git bash (as well as a regular msys2).

**Comment by ttaylorr** [comment]
Sorry, I added this to the `v1.5.4` milestone by mistake. This fix requires Go 1.8 to be released, which will happen in the coming weeks. Once that is ready, we'll cut a point release with Go 1.8 that will fix this issue. 👍

**Comment by iamsergio** [comment]
So go 1.8 is out now, if I clone git-lfs from git will it use my system go (1.8) or do I need to wait for a git-lfs release ?

**Comment by technoweenie** [comment]
@iamsergio If you have go 1.8, the easiest way to build Git LFS is just `go get github.com/git-lfs/git-lfs`. Assuming `$GOPATH/bin` is in your `$PATH` somewhere, that should work just fine. You'll be on the `master` branch though, which is `v2.0-pre`. If you want to get on an official release version, built with your go1.8:

```sh
$ go get github.com/git-lfs/git-lfs
$ cd $GOPATH/src/github.com/git-lfs/git-lfs
$ git checkout v1.5.6
$ go get github.com/git-lfs/git-lfs
```
