### ISSUE TITLE
Specific sequence of commands leads to git-lfs error (backtrace) on one machine, works on other

### ISSUE THREAD

**Issue by JonasT** [git-lfs/git-lfs#1803]
When running the following sequence on my server automated by a python script, I get a git-lfs crash with backtrace:
```
git init .
git lfs install --skip-smudge
git remote
git remote add source https://gitlfsiauthenticatednotsupported:noneneeded@gitlab.wobble.ninja/JonasT/ChiCraft.git
git remote update
git remote
git remote add target https://JonasT:<RETRACTED>@github.com/ChiCraft/ChiCraft.git
git remote update
git fetch source
git checkout master
git-lfs fetch --all
```

This leads to the following error:
```
Scanning for all objects ever referenced...
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
panic(0x7a0540, 0xc4200143e0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
strings.Repeat(0x800fa8, 0x1, 0xffffffffffffffef, 0x2, 0x2)
	/usr/local/go/src/strings/strings.go:420 +0x49
github.com/git-lfs/git-lfs/progress.(*Spinner).update(0xc420045a40, 0xbbfda0, 0xc4200d2a00, 0xc420014398, 0x1, 0xc4200143a0, 0xf)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/progress/spinner.go:57 +0x1b0
github.com/git-lfs/git-lfs/progress.(*Spinner).Spin(0xc420045a40, 0xbbfda0, 0xc4200d2a00)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/progress/spinner.go:29 +0xc8
github.com/git-lfs/git-lfs/progress.(*Spinner).Print(0xc420045a40, 0xbbfda0, 0xc4200d2a00, 0xc4200143a0, 0xf)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/progress/spinner.go:23 +0x5f
github.com/git-lfs/git-lfs/commands.scanAll(0x10, 0x0, 0x0)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:226 +0x357
github.com/git-lfs/git-lfs/commands.fetchAll(0xc420090000)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:201 +0x26
github.com/git-lfs/git-lfs/commands.fetchCommand(0xc4200ee9c0, 0xc42005db10, 0x0, 0x1)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:76 +0x702
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc4200ee9c0, 0xc42005da90, 0x1, 0x1, 0xc4200ee9c0, 0xc42005da90)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x170
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42006bba0, 0xc420045ed0, 0x1)
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x380
github.com/git-lfs/git-lfs/commands.Run()
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/commands/run.go:66 +0x196
main.main()
	/tmp/docker_run/src/github.com/git-lfs/git-lfs/amd64/obj-x86_64-linux-gnu/src/github.com/git-lfs/git-lfs/git-lfs.go:33 +0x111
```
Sadly, doing the same on my local laptop I cannot reproduce this issue.

**Comment by ttaylorr** [comment]
Not quite sure what's going on yet, but one thing that stuck out to me:

> ```
> git-lfs fetch -alll
> ```

has one too many `l`'s. 😄

**Comment by JonasT** [comment]
I use a python script to execute those commands on the server for mirroring (pulling updates from source and pushing them to target).

When creating this bug report, I typed the commands from the log of my self-written python script which runs them where they are shown in the format `['git', 'fetch', 'source']`, so I rewrote them for better reading in this bug report. In conclusion, the actual command run was indeed `git-lfs fetch --all`.

**Comment by ttaylorr** [comment]
> ```
> Scanning for all objects ever referenced...
> panic: runtime error: makeslice: len out of range
> ```

The above error means that somewhere, LFS tried to allocate a slice with an invalid length, i.e., `len<0`, greater than the available memory, etc. Looking at the stack trace from above, this happens within LFS's `progress` package when it tries to determine how many padding characters to print to the terminal. I patched this issue in #1806, which I will backport into the v1.5.4 release today 👍.

**Comment by ttaylorr** [comment]
[v1.5.4][1] has been released, and this issue is resolved 👍 .

[1]: https://github.com/git-lfs/git-lfs/releases/tag/v1.5.4

**Comment by JonasT** [comment]
Thanks, I tested the updated version and it seems to be fixed for me!

**Comment by ttaylorr** [comment]
So glad to hear! 🎉
