### ISSUE TITLE
NoClassDefFoundError while Migrating existing repository data to LFS [Using git-lfs-migrate]

### ISSUE THREAD

**Issue by samsonpaul87** [git-lfs/git-lfs#1899]
Hi,
I have completed following steps (https://github.com/git-lfs/git-lfs/wiki/Tutorial#migrating-existing-repository-data-to-lfs) to migrate existing repository data to LFS, mentioned here. 

- Install Java 1.8 or later
- Download the latest binaries from here
- Do a mirror clone of the repository to rewrite: git clone --mirror git@github.com:bozaro/git-lfs-migrate.git 

I ended up with NoClassDefFoundError while trying to run the  following step 

- Rewrite e.g. all *.mp4 video files in the repository:

Following is my full stack. Please note that, I have changed the .git file name and project name, due to security issues.
```
admin@admin-ThinkPad:~/MyProjects/MiProject_Repo_Mirror$ java -jar git-lfs-migrate.jar      -s miproject_android_studio.git      -d miproject_android_studio_lfs-migrate-converted.git      -g https://myrepository@bitbucket.org/miproject/miproject_android_studio_lfs-migrate-converted.git      "*.sqlite"      "*.sqlite.zip"
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.HttpClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
admin@admin-ThinkPad:~/MyProjects/MiProject_Repo_Mirror$ 


```

**Comment by ttaylorr** [comment]
Hi @samsonpaul87, thanks for opening this and sorry that you're having trouble.

This error is actually coming from `git-lfs-migrate`, which we do not provide support for here. My recommendation would be that you re-open this issue in https://github.com/bozaro/git-lfs-migrate, instead.

**Comment by samsonpaul87** [comment]
Thank you @ttaylorr . I have created a new ticket there https://github.com/bozaro/git-lfs-migrate/issues/28
