### ISSUE TITLE
Adding files on macOS resulting in "clean filter 'lfs' failed"

### ISSUE THREAD

**Issue by tonygod** [git-lfs/git-lfs#2172]
I am having this problem on a macOS (Sierra) trying to add files to a repository:

```
$ git lfs add Assets/PostProcessing/       <-- a directory with multiple files in it

fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x2e30934ec508 pc=0x1039b]

runtime stack:
runtime.throw(0x62e660, 0x2a)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x836680)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x836680, 0x80, 0x100000000, 0x839630)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x70000ac92dc8)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x836680, 0x80, 0x10100000000, 0x15d4c)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0x100000, 0x1, 0x42)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc820016000)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:245 fp=0xc82004af68 sp=0xc82004af60
runtime.mallocgc(0x100000, 0x418c00, 0xc800000001, 0x10)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:665 +0x9eb fp=0xc82004b040 sp=0xc82004af68
runtime.newarray(0x418c00, 0x100000, 0xc82007a200)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/malloc.go:798 +0xc9 fp=0xc82004b080 sp=0xc82004b040
runtime.makeslice(0x4073c0, 0x100000, 0x100000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/slice.go:32 +0x165 fp=0xc82004b0d0 sp=0xc82004b080
github.com/github/git-lfs/errutil.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:578 +0x4a fp=0xc82004b120 sp=0xc82004b0d0
github.com/github/git-lfs/errutil.newWrappedError(0x9b0000, 0xc82013e150, 0x601ce0, 0x21, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:326 +0x1a3 fp=0xc82004b210 sp=0xc82004b120
github.com/github/git-lfs/errutil.NewNotAPointerError(0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:518 +0x50 fp=0xc82004b270 sp=0xc82004b210
github.com/github/git-lfs/lfs.decodeKVData(0xc82005ec00, 0x400, 0x400, 0xc820108fc0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:236 +0xd9 fp=0xc82004b4c8 sp=0xc82004b270
github.com/github/git-lfs/lfs.decodeKV(0xc82005ec00, 0x400, 0x400, 0xc82005ec00, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:139 +0x5f fp=0xc82004b6f8 sp=0xc82004b4c8
github.com/github/git-lfs/lfs.DecodeFrom(0x970028, 0xc82007a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:120 +0x17b fp=0xc82004b790 sp=0xc82004b6f8
github.com/github/git-lfs/lfs.copyToTemp(0x970028, 0xc82007a000, 0x1bbf, 0x0, 0x0, 0x0, 0x0, 0xc82007a1f8, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_clean.go:79 +0x2b6 fp=0xc82004b910 sp=0xc82004b790
github.com/github/git-lfs/lfs.PointerClean(0x970028, 0xc82007a000, 0x7fff5fbffaa9, 0x3a, 0x1bbf, 0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer_clean.go:54 +0x979 fp=0xc82004baf8 sp=0xc82004b910
github.com/github/git-lfs/commands.cleanCommand(0x82aa00, 0xc8200df1e0, 0x1, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_clean.go:44 +0x264 fp=0xc82004bcf0 sp=0xc82004baf8
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0x82aa00, 0xc8200df060, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x3f4 fp=0xc82004bdb8 sp=0xc82004bcf0
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0x82e2e0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x46a fp=0xc82004bec0 sp=0xc82004bdb8
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:112 +0x23 fp=0xc82004bee0 sp=0xc82004bec0
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:33 +0x12e fp=0xc82004bf50 sp=0xc82004bee0
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc82004bfa0 sp=0xc82004bf50
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004bfa8 sp=0xc82004bfa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.6.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 23 [select, locked to thread]:
runtime.gopark(0x674f58, 0xc820024f28, 0x58bad0, 0x6, 0x18, 0x2)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820024f28, 0x0, 0x18)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820024f28)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/signal1_unix.go:279 +0x32c
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 24 [chan receive]:
main.main.func1(0xc82006f320, 0xc820071b00)
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:21 +0x66
created by main.main
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:31 +0x129
error: external filter 'git-lfs clean -- %f' failed 2
error: external filter 'git-lfs clean -- %f' failed
fatal: Assets/PostProcessing/Resources/Bluenoise64/LDR_LLL1_4.png: clean filter 'lfs' failed
```

```
$ git version
git version 2.12.2
```

```
$ which git
/usr/local/bin/git
```

```
$ which git-lfs
/usr/local/bin/git-lfs
```

I have tried the command multiple times, and it seems it fails on a different file each time.  The files exist in the location as expected, so I don't understand why the clean is failing.

**Comment by ttaylorr** [comment]
@tonygod thanks for opening this and sorry that you're having trouble. Looking at the stack trace, it looks like the last line of LFS that is executed before Go runs into a malloc issue is:

```
github.com/github/git-lfs/errutil.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:578 +0x4a fp=0xc82004b120 sp=0xc82004b0d0
github.com/github/git-lfs/errutil.newWrappedError(0x9b0000, 0xc82013e150, 0x601ce0, 0x21, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:326 +0x1a3 fp=0xc82004b210 sp=0xc82004b120
github.com/github/git-lfs/errutil.NewNotAPointerError(0x0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:518 +0x50 fp=0xc82004b270 sp=0xc82004b210
github.com/github/git-lfs/lfs.decodeKVData(0xc82005ec00, 0x400, 0x400, 0xc820108fc0, 0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:236 +0xd9 fp=0xc82004b4c8 sp=0xc82004b270
github.com/github/git-lfs/lfs.decodeKV(0xc82005ec00, 0x400, 0x400, 0xc82005ec00, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/lfs/pointer.go:139 +0x5f fp=0xc82004b6f8 sp=0xc82004b4c8
```

But beyond that, it looks like a Go crash. The error on L236 of `lfs/pointer.go` indicates that the file LFS tried to parse wasn't a pointer file, which may or may not be an error, depending on whether or not this is a `git add` or `git reset`.

Before we dive in deeper, let's make sure you're on the latest version of LFS. Could you:

```sh
$ brew update git-lfs && brew upgrade git-lfs
```

and then post the output of:

```sh
$ git lfs version
```

and try again?

**Comment by tonygod** [comment]
Thanks @ttaylorr.  I think you are right.  I have already added all the files individually, but then realized when I tried to merge the branch I was still having problems with git-lfs.  I followed your instructions from another issue to remove an older git-lfs and re-link to the new one and now the merge problem is gone.  I think this can be closed.

**Comment by tonygod** [comment]
Just did another add and problem is gone now.
