### ISSUE TITLE
Long Paths Support not working

### ISSUE THREAD

**Issue by BstlWstl** [git-lfs/git-lfs#2213]
Hi,
i've installed the latest Git Version and enabled LFS support for my Repo to track Matlab mat files. When adding a File with `git add` i got the following error:
```
$ git add ./software/aaaaaaaaaaaaa/bbbbbbbbb/cccc/dddd_ddddddddd/eeeeeeeeeee/ffffffffffffffff/ggggg/hhhhhh_i_jjjj_kkkk_llllllllll_mmmmmmmmmmmmmmmmmmm-nn_ooo_pppp/qqqqqq_r_ssss_tttt_uuuuuuuuuu_vvvvvvvvvvvvvvvvvvv-ww_xxx_yyyy.mat
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/git-lfs/git-lfs/git.(*FilterProcessScanner).readRequest(0xc04213dac0, 0x737365636375, 0xc04213b750, 0x0)
        C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/git/filter_process_scanner.go:181 +0x279
github.com/git-lfs/git-lfs/git.(*FilterProcessScanner).Scan(0xc04213dac0, 0x8a9c97)
        C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/git/filter_process_scanner.go:143 +0x7e
github.com/git-lfs/git-lfs/commands.filterCommand(0xc0420f0d00, 0xaee238, 0x0, 0x0)
        C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_filter_process.go:51 +0x2d1
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc0420f0d00, 0xaee238, 0x0, 0x0, 0xc0420f0d00, 0xaee238)
        C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x16d
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042023d40, 0xc042093f10, 0x1)
        C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x341
github.com/git-lfs/git-lfs/commands.Run()
        C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/src/github.com/git-lfs/git-lfs/commands/run.go:68 +0x1ad
main.main()
        C:/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35 +0x118
```
My guess is that is has something to do with the length of the filename.
The above string in the add command has 218 characters. When looking at the absolute path of the file the length is rising to 268 characters.
I've set up `longpaths=true` in `config `file of the `.git` folder. But it does not seem to work.

I'm on this environment:
```
$ git lfs env
git-lfs/2.1.0 (GitHub; windows amd64; go 1.8.1; git bd2c9987)
git version 2.13.0.windows.1

LocalWorkingDir=C:\Users\xxxxxxx\Projekte\JenkinsTest\firmware
LocalGitDir=C:\Users\xxxxxxx\Projekte\JenkinsTest\firmware\.git
LocalGitStorageDir=C:\Users\xxxxxxx\Projekte\JenkinsTest\firmware\.git
LocalMediaDir=C:\Users\xxxxxxx\Projekte\JenkinsTest\firmware\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Users\xxxxxxx\Projekte\JenkinsTest\firmware\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by ttaylorr** [comment]
@BstlWstl thanks for opening this and sorry that you're having trouble. Git LFS should support long-style Windows paths, but I'm curious what's going on here. The stacktrace that you posted was very helpful, so I'm guessing this is either:

1. Git incorrectly sending the path to LFS, or
2. LFS failing to parse the path that Git sent correctly.

Could your re-run your `git add` command with `GIT_TRACE_PACKET=1` in front?

**Comment by BstlWstl** [comment]
@ttaylorr thanks for the quick reply.
Please find attached the requested log.
The strange thing i've noticed is that with the `GIT_TRACE_PACKET=1` it seems to work. When i take a look at `git status` i can commit it(see log file). 
One thins i've noticed in the log is that in line 28 there is a command prompt pattern. I have no idea if that is correct. Maybe the buffer for the console is to short.

I hope this will help you to find the Bug.
Thanks.

[GitTrackPacket_Output.txt](https://github.com/git-lfs/git-lfs/files/995261/GitTrackPacket_Output.txt)

**Comment by ttaylorr** [comment]
> Maybe the buffer for the console is to short.

I think that this is likely the problem.
