### ISSUE TITLE
 fatal error: concurrent map writes

### ISSUE THREAD

**Issue by canyou2014** [git-lfs/git-lfs#2489]
Encountered in `git lfs fetch`.
```
 fatal error: concurrent map writes

goroutine 43 [running]:
runtime.throw(0x8b3038, 0x15)
        /usr/local/go/src/runtime/panic.go:596 +0x9c fp=0xc04236d768 sp=0xc04236d748
runtime.mapassign(0x834e80, 0xc042160000, 0xc04236d838, 0x0)
        /usr/local/go/src/runtime/hashmap.go:499 +0x66e fp=0xc04236d808 sp=0xc04236d768
github.com/git-lfs/git-lfs/lfsapi.(*credentialCacher).Approve(0xc042109dc0, 0x0, 0xaa67a0, 0xc042109dc0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/creds.go:77 +0xbf fp=0xc04236d858 sp=0xc04236d808
github.com/git-lfs/git-lfs/lfsapi.(*Client).DoWithAuth(0xc042037a00, 0xc042272018, 0x6, 0xc042001800, 0x4000105, 0x0, 0xffffffffffffffff)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:64 +0x223 fp=0xc04236d9f0 sp=0xc04236d858
github.com/git-lfs/git-lfs/tq.(*adapterBase).doHTTP(0xc0421ab680, 0xc0422deb40, 0xc042001800, 0x11, 0xc042001800, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:205 +0xa7 fp=0xc04236da38 sp=0xc04236d9f0
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download(0xc042124220, 0xc0422deb40, 0xc04211de90, 0x0, 0xc0420040f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/basic_download.go:113 +0x3d2 fp=0xc04236dd40 sp=0xc04236da38
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer(0xc042124220, 0x0, 0x0, 0xc0422deb40, 0xc04211de90, 0x0, 0xc04213c100, 0x80)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/basic_download.go:49 +0xc3 fp=0xc04236dda0 sp=0xc04236dd40
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker(0xc0421ab680, 0x2, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:171 +0x5f9 fp=0xc04236dfc0 sp=0xc04236dda0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc04236dfc8 sp=0xc04236dfc0
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Begin
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:84 +0x338

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0422aa0dc)
        /usr/local/go/src/runtime/sema.go:47 +0x3b
sync.(*WaitGroup).Wait(0xc0422aa0d0)
        /usr/local/go/src/sync/waitgroup.go:131 +0x81
github.com/git-lfs/git-lfs/tq.(*TransferQueue).Wait(0xc0422aa000)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:595 +0x54
github.com/git-lfs/git-lfs/commands.fetchAndReportToChan(0xc042216000, 0x7, 0x8, 0xc042160930, 0x0, 0x8)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:324 +0x48d
github.com/git-lfs/git-lfs/commands.fetchRef(0xc0421663c0, 0x28, 0xc042160930, 0x1)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:144 +0x9d
github.com/git-lfs/git-lfs/commands.fetchCommand(0xc0420fc000, 0xaf12d8, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:88 +0x268
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc0420fc000, 0xaf12d8, 0x0, 0x0, 0xc0420fc000, 0xaf12d8)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x16d
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0420391e0, 0xc04209bf10, 0x1)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x341
github.com/git-lfs/git-lfs/commands.Run()
        /home/golang/lib/src/github.com/git-lfs/git-lfs/commands/run.go:68 +0x1ad
main.main()
        /home/golang/lib/src/github.com/git-lfs/git-lfs/git-lfs.go:35 +0x118

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x10b
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 19 [chan receive]:
main.main.func1(0xc04203aa80, 0xc04203d5a0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/git-lfs.go:23 +0x6f
created by main.main
        /home/golang/lib/src/github.com/git-lfs/git-lfs/git-lfs.go:33 +0x113

goroutine 44 [chan receive]:
github.com/git-lfs/git-lfs/tq.(*TransferQueue).addToAdapter.func1(0xc0422ded20, 0xc0422aa000, 0xc0422ee7c0, 0x7, 0x7, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:415 +0x140
created by github.com/git-lfs/git-lfs/tq.(*TransferQueue).addToAdapter
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:418 +0x239

goroutine 53 [select]:
net/http.(*persistConn).readLoop(0xc04232c6c0)
        /usr/local/go/src/net/http/transport.go:1599 +0x9f3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1117 +0xa3c

goroutine 49 [chan receive]:
github.com/git-lfs/git-lfs/tq.(*TransferQueue).errorCollector(0xc0422aa000)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:619 +0x70
created by github.com/git-lfs/git-lfs/tq.(*TransferQueue).run
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:630 +0xc5

goroutine 42 [syscall, locked to thread]:
syscall.Syscall(0x76ad14d0, 0x2, 0x204, 0xffffffff, 0x0, 0x527d7e, 0x451ec0, 0xc0422f5530)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
syscall.WaitForSingleObject(0x204, 0xffffffff, 0xc042338dc0, 0xc0422ed320, 0x3)
        /usr/local/go/src/syscall/zsyscall_windows.go:718 +0x6d
os.(*Process).wait(0xc042337890, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/exec_windows.go:18 +0xa0
os.(*Process).Wait(0xc042337890, 0x0, 0x0, 0x8d1b10)
        /usr/local/go/src/os/exec.go:115 +0x32
os/exec.(*Cmd).Wait(0xc042338dc0, 0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:435 +0x69
github.com/git-lfs/git-lfs/lfsapi.(*commandCredentialHelper).exec(0xc042114c00, 0x8ac260, 0x7, 0x0, 0x0, 0xc0421ee6c0, 0xc0422f5848)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/creds.go:118 +0x7ed
github.com/git-lfs/git-lfs/lfsapi.(*commandCredentialHelper).Approve(0xc042114c00, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/creds.go:98 +0x51
github.com/git-lfs/git-lfs/lfsapi.(*credentialCacher).Approve(0xc042109dc0, 0x0, 0xaa67a0, 0xc042109dc0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/creds.go:75 +0x49
github.com/git-lfs/git-lfs/lfsapi.(*Client).DoWithAuth(0xc042037a00, 0xc042272018, 0x6, 0xc0421cd100, 0x5000104, 0x0, 0xffffffffffffffff)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/auth.go:64 +0x223
github.com/git-lfs/git-lfs/tq.(*adapterBase).doHTTP(0xc0421ab680, 0xc0422deae0, 0xc0421cd100, 0x11, 0xc0421cd100, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:205 +0xa7
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download(0xc042124220, 0xc0422deae0, 0xc04211de90, 0x0, 0xc042124270, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/basic_download.go:113 +0x3d2
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer(0xc042124220, 0x0, 0x0, 0xc0422deae0, 0xc04211de90, 0x0, 0xc04211f0c0, 0x6)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/basic_download.go:49 +0xc3
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker(0xc0421ab680, 0x1, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:171 +0x5f9
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Begin
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:84 +0x338

goroutine 50 [chan receive]:
github.com/git-lfs/git-lfs/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0xc0422aa000, 0xc0422b2000, 0x7, 0x64, 0x0, 0x64, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:363 +0x1084
github.com/git-lfs/git-lfs/tq.(*TransferQueue).collectBatches(0xc0422aa000)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:258 +0x2e6
created by github.com/git-lfs/git-lfs/tq.(*TransferQueue).run
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:631 +0xe7

goroutine 54 [select]:
net/http.(*persistConn).writeLoop(0xc04232c6c0)
        /usr/local/go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa61

goroutine 41 [runnable]:
sync.(*Mutex).Unlock(0xc0423494ac)
        /usr/local/go/src/sync/mutex.go:104 +0xbb
net/http.(*body).Read(0xc042349480, 0xc0423ba000, 0x8000, 0x8000, 0xf45, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:753 +0x126
net/http.(*bodyEOFSignal).Read(0xc0423494c0, 0xc0423ba000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:2035 +0xf0
github.com/git-lfs/git-lfs/lfsapi.tracedRead(0xaa29e0, 0xc0423494c0, 0xc0423ba000, 0x8000, 0x8000, 0xaa2d60, 0xc042054010, 0x0, 0x0, 0xc0422f9820, ...)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/verbose.go:115 +0x77
github.com/git-lfs/git-lfs/lfsapi.(*tracedResponse).Read(0xc04234ce10, 0xc0423ba000, 0x8000, 0x8000, 0xc0422f98c0, 0x40f39c, 0xb10490)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/lfsapi/verbose.go:104 +0xbc
github.com/git-lfs/git-lfs/tools.(*RetriableReader).Read(0xc042115cb0, 0xc0423ba000, 0x8000, 0x8000, 0x28276de946, 0xc04202b800, 0xb10490)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tools/iotools.go:88 +0x5c
github.com/git-lfs/git-lfs/tools.(*HashingReader).Read(0xc042168da0, 0xc0423ba000, 0x8000, 0x8000, 0xc0422f9901, 0xc0423ba000, 0x83dd20)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tools/iotools.go:67 +0x5c
github.com/git-lfs/git-lfs/progress.(*CallbackReader).Read(0xc04235e510, 0xc0423ba000, 0x8000, 0x8000, 0x8000, 0x8000, 0x28)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/progress/copycallback.go:73 +0x5d
io.copyBuffer(0xaa2d60, 0xc042288030, 0xaa22e0, 0xc04235e510, 0xc0423ba000, 0x8000, 0x8000, 0x86ea00, 0xb10401, 0xc04235e510)
        /usr/local/go/src/io/io.go:390 +0x107
io.Copy(0xaa2d60, 0xc042288030, 0xaa22e0, 0xc04235e510, 0x20, 0x86a980, 0xc04213dc01)
        /usr/local/go/src/io/io.go:360 +0x6f
github.com/git-lfs/git-lfs/tools.CopyWithCallback(0xaa2d60, 0xc042288030, 0xaa2360, 0xc042168da0, 0xa807, 0xc042168dc0, 0x0, 0xc0422f9aa8, 0xc0422f9b60)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tools/iotools.go:40 +0xb8
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download(0xc042124220, 0xc0422deba0, 0xc04211de90, 0x0, 0xc042288030, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/basic_download.go:206 +0x9cd
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer(0xc042124220, 0x0, 0x0, 0xc0422deba0, 0xc04211de90, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/basic_download.go:49 +0xc3
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker(0xc0421ab680, 0x0, 0x0, 0x0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:171 +0x5f9
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Begin
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:84 +0x338

goroutine 40 [runnable]:
github.com/git-lfs/git-lfs/progress.(*ProgressMeter).writer(0xc042278000)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/progress/meter.go:185 +0x121
created by github.com/git-lfs/git-lfs/progress.(*ProgressMeter).Start
        /home/golang/lib/src/github.com/git-lfs/git-lfs/progress/meter.go:110 +0x63

goroutine 45 [semacquire]:
sync.runtime_Semacquire(0xc04211de8c)
        /usr/local/go/src/runtime/sema.go:47 +0x3b
sync.(*WaitGroup).Wait(0xc04211de80)
        /usr/local/go/src/sync/waitgroup.go:131 +0x81
github.com/git-lfs/git-lfs/tq.(*adapterBase).Add.func1(0xc0422ee7c0, 0x7, 0x7, 0xc0421ab680, 0xc0422dede0)
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:111 +0x165
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Add
        /home/golang/lib/src/github.com/git-lfs/git-lfs/tq/adapterbase.go:114 +0xb2

goroutine 66 [select]:
net/http.(*persistConn).readLoop(0xc04232c480)
        /usr/local/go/src/net/http/transport.go:1599 +0x9f3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1117 +0xa3c

goroutine 67 [select]:
net/http.(*persistConn).writeLoop(0xc04232c480)
        /usr/local/go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa61

goroutine 16 [select]:
net/http.(*persistConn).readLoop(0xc042300c60)
        /usr/local/go/src/net/http/transport.go:1599 +0x9f3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1117 +0xa3c

goroutine 81 [select]:
net/http.(*persistConn).writeLoop(0xc042300c60)
        /usr/local/go/src/net/http/transport.go:1704 +0x441
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1118 +0xa61

goroutine 71 [syscall, locked to thread]:
syscall.Syscall6(0x76ac09a0, 0x5, 0x1e8, 0xc0420dd400, 0x200, 0xc042345d3c, 0x0, 0x0, 0x0, 0x3, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
syscall.ReadFile(0x1e8, 0xc0420dd400, 0x200, 0x200, 0xc042345d3c, 0x0, 0xc042345d58, 0xc042345d50)
        /usr/local/go/src/syscall/zsyscall_windows.go:311 +0xe6
syscall.Read(0x1e8, 0xc0420dd400, 0x200, 0x200, 0x42a536, 0x8d0cc0, 0xc042345dc0)
        /usr/local/go/src/syscall/syscall_windows.go:296 +0x6f
os.(*File).read(0xc0421242c8, 0xc0420dd400, 0x200, 0x200, 0x0, 0x0, 0x0)
        /usr/local/go/src/os/file_windows.go:289 +0xd0
os.(*File).Read(0xc0421242c8, 0xc0420dd400, 0x200, 0x200, 0x0, 0x0, 0xc042345e60)
        /usr/local/go/src/os/file.go:101 +0x7d
bytes.(*Buffer).ReadFrom(0xc04232aee0, 0xaa2d20, 0xc0421242c8, 0xc70028, 0xc04232aee0, 0x1)
        /usr/local/go/src/bytes/buffer.go:179 +0x167
io.copyBuffer(0xaa1a60, 0xc04232aee0, 0xaa2d20, 0xc0421242c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:384 +0x2d2
io.Copy(0xaa1a60, 0xc04232aee0, 0xaa2d20, 0xc0421242c8, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:360 +0x6f
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
        /usr/local/go/src/os/exec/exec.go:254 +0x54
os/exec.(*Cmd).Start.func1(0xc042338dc0, 0xc0422ed320)
        /usr/local/go/src/os/exec/exec.go:371 +0x2e
created by os/exec.(*Cmd).Start
        /usr/local/go/src/os/exec/exec.go:372 +0x55e

```
Environment:
```
Windows7
git 2.12.0
git-lfs 2.2.0-pre
```
And the Git-LFS version was compiled using go 1.8.1 in Ubuntu 12.04.5 LTS.

This error occurred frequently when there were many small size objects.
Was this caused by no wrapper struct around map to provide thread safety?  Look at [here](https://github.com/git-lfs/git-lfs/blob/master/lfsapi/creds.go#L77 "here").

**Comment by ttaylorr** [comment]
Hi @canyou2014, thanks for opening this. Can you ensure that you are on Go 1.8.3 and Git LFS v2.2.1 (instead of 1.8.1 and 2.2.0-pre, respectively) and let me know if you see the error again?
