### ISSUE TITLE
Intermittent checkout (smudge) failures due to connection reset by peer

### ISSUE THREAD

**Issue by ubershmekel** [git-lfs/git-lfs#2542]
This happened 2 times out of the recent 5 jenkins test runs. Feels bad to have tests fail because of this, I might need to add retries at the checkout phase in jenkins somehow. I don't know how to discern if this is a github git-lfs issue or a connectivity issue.

The jenkins reported error:

```
 > /usr/bin/git checkout -f 57469182508c2c08714f4dff87726be4d32064ec
FATAL: Could not checkout 57469182508c2c08714f4dff87726be4d32064ec
hudson.plugins.git.GitException: Could not checkout 57469182508c2c08714f4dff87726be4d32064ec
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2101)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1139)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1278)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f 57469182508c2c08714f4dff87726be4d32064ec" returned status code 128:
stdout: 
stderr: Downloading packages/api/cat.jpg (6.27 KB)
Downloading packages/api/test/testvid.mp4 (8.73 MB)
Error downloading object: packages/api/test/testvid.mp4 (d6b693191b89a7832d04d94068a91901d3a597adde9c8e38be089c42dae511d3)

Errors logged to /var/lib/jenkins/workspace/app-server/.git/lfs/objects/logs/20170830T194013.922224166.log
Use `git lfs logs last` to view the log.
```

The output from `git lfs logs last`:

```
git-lfs/1.3.1 (GitHub; linux amd64; go 1.6.3; git 9c9dffb)
git version 1.9.1

$ git-lfs smudge -- packages/api/test/testvid.mp4
Error downloading object: packages/api/test/testvid.mp4 (d6b693191b89a7832d04d94068a91901d3a597adde9c8e38be089c42dae511d3)

Error buffering media file: cannot write data to tempfile "/var/lib/jenkins/workspace/app-server/.git/lfs/objects/incomplete/d6b693191b89a7832d04d94068a91901d3a597adde9c8e38be089c42dae511d3.tmp": read tcp 192.168.7.35:45816->54.231.98.160:443: read: connection reset by peer
goroutine 1 [running]:
github.com/github/git-lfs/errutil.Stack(0x0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/errutil/errors.go:579 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f2e729c6270, 0xc82002a048, 0x7f2e727a22d8, 0xc820452260)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:223 +0xf80
github.com/github/git-lfs/commands.logPanic(0x7f2e727a22d8, 0xc820452260, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:187 +0x412
github.com/github/git-lfs/commands.handlePanic(0x7f2e727a22d8, 0xc820452260, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:162 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f2e727a22d8, 0xc820452260, 0x9fd460, 0x21, 0xc820043c98, 0x2, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:97 +0x82
github.com/github/git-lfs/commands.smudgeCommand(0xc28000, 0xc8200ec540, 0x1, 0x2)
	/Users/rick/go/src/github.com/github/git-lfs/commands/command_smudge.go:79 +0xdc6
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc28000, 0xc8200ec3a0, 0x2, 0x2, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x3f4
github.com/github/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc291e0, 0x0, 0x0)
	/Users/rick/go/src/github.com/github/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
	/Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:112 +0x23
main.main()
	/Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:33 +0x12e
```

**Comment by technoweenie** [comment]
Oh dang, you're on an ancient version of LFS (1.3.1). Try upgrading to the latest, which has much better retry capabilities.

**Comment by ubershmekel** [comment]
Thank you. I've updated. Now we wait.

**Comment by kiloreux** [comment]
@ubershmekel any update ?

**Comment by ubershmekel** [comment]
I have not seen connection reset by peer since I upgraded git and git-lfs. Jenkins fails sometimes to check out because of its own internal time outs, but git-lfs with enough time does complete what it's asked. I'll close for now. Thank you.
