### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by cmruffin** [git-lfs/git-lfs#2597]
I am gettting some fundamental error under some conditions in my repository.

```
C:\Q\10nm\working2\10nmServerTrunk>git lfs migrate import --include="*.chm,*.pdf,*.bin,*.BIN,*.bmp,*.dll,*.efi,*.EFI,*.exe,*.fd,*.fv,*.Fv,*.
lib,*.raw,*.zip,*.data,*.xml" --everything
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/git-lfs/git-lfs/vendor/golang.org/x/exp/mmap.Open(0xc0421cd2d0, 0x67, 0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/golang.org/x/exp/mmap/mmap_windows.go:111 +0x2b4
github.com/git-lfs/git-lfs/git/odb/pack.NewSet(0xc04211ac60, 0x2f, 0xc042095b90, 0x4f26b6, 0xc042095bd0)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git/odb/pack/set.go:57 +0x370
github.com/git-lfs/git-lfs/git/odb.FromFilesystem(0xc04211ac60, 0x2f, 0x2, 0xc04211ac60, 0x2f)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git/odb/object_db.go:36 +0x40
github.com/git-lfs/git-lfs/commands.getObjectDatabase(0xafef40, 0xc04204e010, 0xc04211e340)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_migrate.go:52 +0xf0
github.com/git-lfs/git-lfs/commands.migrateImportCommand(0xc042033520, 0xc042104440, 0x0, 0x2)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_migrate_import.go:24 +0x61
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc042033520, 0xc042104260, 0x2, 0x2, 0xc042033520, 0xc042104260
)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x16d
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042033860, 0xc042095f10, 0x1)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x341
github.com/git-lfs/git-lfs/commands.Run()
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68 +0x1ad
main.main()
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35 +0x118
```

```

C:\Q\10nm\working2\10nmServerTrunk>git lfs env
git-lfs/2.3.0 (GitHub; windows amd64; go 1.8.3; git 4dd2bf73)
git version 2.13.3.windows.1

Endpoint=https://ubit-artifactory-or.intel.com/artifactory/api/lfs/intel-edk2-lfs-local (auth=none)
LocalWorkingDir=C:\Q\10nm\working2\10nmServerTrunk
LocalGitDir=C:\Q\10nm\working2\10nmServerTrunk\.git
LocalGitStorageDir=C:\Q\10nm\working2\10nmServerTrunk\.git
LocalMediaDir=C:\Q\10nm\working2\10nmServerTrunk\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\Q\10nm\working2\10nmServerTrunk\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\Q\10nm\working2\10nmServerTrunk\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by technoweenie** [comment]
Oof, that's a low level mmap bug.

https://github.com/golang/exp/blob/50c28f97489115b511c3104aafe83f148deb39a9/mmap/mmap_windows.go#L111

Is it repeatable?

As a crappy workaround, you could try running this on linux or mac.

**Comment by cmruffin** [comment]
It is repeatable in most cases. I seem to be able to get the repo into a 
state where I can't reproduce the issue.

**Comment by technoweenie** [comment]
A couple more thoughts:

Assuming this error is repeatable, does it also blow up on `info`?

```sh
$ git lfs migrate info --include="*.chm,*.pdf,*.bin,*.BIN,*.bmp,*.dll,*.efi,*.EFI,*.exe,*.fd,*.fv,*.Fv,*.
lib,*.raw,*.zip,*.data,*.xml" --everything
```

I wonder if the size of your packfiles exceeds the available memory of your system? There may be a better way to mmap the packfiles.

**Comment by cmruffin** [comment]
@technoweenie I get similar results between import and imfo.

```
Q:\10nm\working3\10nmServerTrunk>git lfs migrate import --include="*.chm,*.pdf,*.bin,*.BIN,*.bmp,*.dll,*.efi,*.EFI,*.exe,*.fd,*.fv,*.Fv" --everything
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/git-lfs/git-lfs/vendor/golang.org/x/exp/mmap.Open(0xc0421d5f10, 0x65, 0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/golang.org/x/exp/mmap/mmap_windows.go:111 +0x2b4
github.com/git-lfs/git-lfs/git/odb/pack.NewSet(0xc04224a090, 0x2d, 0xc042097b90, 0x4f26b6, 0xc042097bd0)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git/odb/pack/set.go:57 +0x370
github.com/git-lfs/git-lfs/git/odb.FromFilesystem(0xc04224a090, 0x2d, 0x2, 0xc04224a090, 0x2d)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git/odb/object_db.go:36 +0x40
github.com/git-lfs/git-lfs/commands.getObjectDatabase(0xafef40, 0xc042004020, 0xc042137100)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_migrate.go:52 +0xf0
github.com/git-lfs/git-lfs/commands.migrateImportCommand(0xc0420fa000, 0xc0420f0860, 0x0, 0x2)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_migrate_import.go:24 +0x61
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc0420fa000, 0xc0420f0680, 0x2, 0x2, 0xc0420fa000, 0xc0420f0680)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x16d
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0420fa340, 0xc042097f10, 0x1)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x341
github.com/git-lfs/git-lfs/commands.Run()
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68 +0x1ad
main.main()
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35 +0x118

Q:\10nm\working3\10nmServerTrunk>git lfs migrate info --include="*.chm,*.pdf,*.bin,*.BIN,*.bmp,*.dll,*.efi,*.EFI,*.exe,*.fd,*.fv,*.Fv" --everything
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/git-lfs/git-lfs/vendor/golang.org/x/exp/mmap.Open(0xc042197ce0, 0x65, 0x0, 0x0, 0x0)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/golang.org/x/exp/mmap/mmap_windows.go:111 +0x2b4
github.com/git-lfs/git-lfs/git/odb/pack.NewSet(0xc04212fb30, 0x2d, 0xc042097b68, 0x4f26b6, 0xc042097ba8)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git/odb/pack/set.go:57 +0x370
github.com/git-lfs/git-lfs/git/odb.FromFilesystem(0xc04212fb30, 0x2d, 0x2, 0xc04212fb30, 0x2d)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git/odb/object_db.go:36 +0x40
github.com/git-lfs/git-lfs/commands.getObjectDatabase(0xafef40, 0xc042004020, 0xc042136c80)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_migrate.go:52 +0xf0
github.com/git-lfs/git-lfs/commands.migrateInfoCommand(0xc042031a00, 0xc0420f0840, 0x0, 0x2)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/command_migrate_info.go:45 +0x64
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc042031a00, 0xc0420f0640, 0x2, 0x2, 0xc042031a00, 0xc0420f0640)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x16d
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc042102000, 0xc042097f10, 0x1)
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x341
github.com/git-lfs/git-lfs/commands.Run()
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/commands/run.go:68 +0x1ad
main.main()
        C:/Users/techn/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35 +0x118

```

**Comment by cmruffin** [comment]
I learned I can do a git gc --aggressive to clear up the problem.

**Comment by cmruffin** [comment]
I see the issue on a 32GB workstation.  A typical packfile is ~1GB.

**Comment by technoweenie** [comment]
Hey @cmruffin, I'm going to see if mmap is even necessary for reading the packfiles. Depending on how that goes, I may have an experimental build for you to try if you don't mind.

**Comment by cmruffin** [comment]
@technoweenie yes I will try your build.

**Comment by technoweenie** [comment]
Can you try this, please? Built from https://github.com/git-lfs/git-lfs/pull/2600. 

[git-lfs-windows-amd64-2.3.0.zip](https://github.com/git-lfs/git-lfs/files/1318615/git-lfs-windows-amd64-2.3.0.zip)

**Comment by svendhhh** [comment]
I'm seeing the same, also on Windows. Any luck with the experimental build @cmruffin? :)

**Comment by cmruffin** [comment]
@technoweenie @svendhhh fix confirmed, thanks for your quick assistance!

**Comment by svendhhh** [comment]
Seems to also work for me now :)

Btw, I was working with this separate git-lfs-migrate project:
https://github.com/bozaro/git-lfs-migrate

It works, but took a long time to complete. Is there any relation between this and the migrate functionality within Git LFS itself?

**Comment by technoweenie** [comment]
It was written by a member of the Git LFS community. We just felt having a version embedded in LFS makes more sense.

I find it hard to believe our version is noticeably faster, so it may be worth adding a logging option to see exactly what is being migrated.

**Comment by technoweenie** [comment]
Thanks for confirming the fix :)
