### ISSUE TITLE
Crash during "git clone" with smudge disabled

### ISSUE THREAD

**Issue by creste** [git-lfs/git-lfs#2838]
Git LFS sometimes crashes when I run this command:

`GIT_TRACE=1 GIT_LFS_SKIP_SMUDGE=1 git clone --recursive ssh://git@git/prj/project.git git-checkout`

Here is the truncated output:
```
13:37:00.626950 git.c:369               trace: built-in: git 'clone' '--recursive' 'ssh://git@git/prj/project.git' 'git-checkout'
Cloning into 'git-checkout'...
13:37:00.628433 run-command.c:369       trace: run_command: 'ssh' 'git@git' 'git-upload-pack '\''/prj/project.git'\'''
13:37:01.059888 run-command.c:369       trace: run_command: 'index-pack' '--stdin' '--fix-thin' '--keep=fetch-pack 26018 on srv' '--check-self-contained-and-connected'
13:37:01.060058 exec_cmd.c:118          trace: exec: 'git' 'index-pack' '--stdin' '--fix-thin' '--keep=fetch-pack 26018 on srv' '--check-self-contained-and-connected'
13:37:01.060694 git.c:369               trace: built-in: git 'index-pack' '--stdin' '--fix-thin' '--keep=fetch-pack 26018 on srv' '--check-self-contained-and-connected'
13:37:14.869109 run-command.c:369       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
13:37:14.869278 exec_cmd.c:118          trace: exec: 'git' 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
13:37:14.870108 git.c:369               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
13:37:14.904712 run-command.c:369       trace: run_command: 'git-lfs filter-process'
13:37:14.904896 run-command.c:228       trace: exec: '/bin/sh' '-c' 'git-lfs filter-process' 'git-lfs filter-process'
13:37:14.908638 trace git-lfs: run_command: 'git' version
13:37:14.910357 trace git-lfs: run_command: 'git' config -l
13:37:14.911491 trace git-lfs: Install hook: pre-push, force=false, path=/home/build/git-checkout/.git/hooks/pre-push
13:37:14.911663 trace git-lfs: Install hook: post-checkout, force=false, path=/home/build/git-checkout/.git/hooks/post-checkout
13:37:14.911783 trace git-lfs: Install hook: post-commit, force=false, path=/home/build/git-checkout/.git/hooks/post-commit
13:37:14.911900 trace git-lfs: Install hook: post-merge, force=false, path=/home/build/git-checkout/.git/hooks/post-merge
13:37:14.911947 trace git-lfs: Initialize filter-process
13:37:14.912011 trace git-lfs: Read filter-process request.
...[truncated]...
13:37:16.692893 trace git-lfs: Read filter-process request.
13:37:16.728135 run-command.c:369       trace: run_command: '.git/hooks/post-checkout' '0000000000000000000000000000000000000000' 'fd4dc823ebac58b5a614f9b24d6429979c2e5aab' '1'
13:37:16.733296 git.c:594               trace: exec: 'git-lfs' 'post-checkout' '0000000000000000000000000000000000000000' 'fd4dc823ebac58b5a614f9b24d6429979c2e5aab' '1'
13:37:16.733319 run-command.c:369       trace: run_command: 'git-lfs' 'post-checkout' '0000000000000000000000000000000000000000' 'fd4dc823ebac58b5a614f9b24d6429979c2e5aab' '1'
13:37:16.736238 trace git-lfs: run_command: 'git' version
13:37:16.738028 trace git-lfs: run_command: 'git' config -l
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x50f2fa]

goroutine 221 [running]:
github.com/git-lfs/git-lfs/filepathfilter.(*Filter).AllowsPattern(0xc420883b30, 0xc420a4eac0, 0x38, 0x2, 0xc420a4eac0, 0x38)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/filepathfilter/filepathfilter.go:130 +0x1ba
github.com/git-lfs/git-lfs/filepathfilter.(*Filter).Allows(0xc420883b30, 0xc420a4eac0, 0x38, 0xc420a4eac0)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/filepathfilter/filepathfilter.go:60 +0x3f
github.com/git-lfs/git-lfs/tools.(*fastWalker).Walk(0xc4201d0240, 0x8a3e00, 0xc420598540, 0x25, 0xd4d1c0, 0xc420232000, 0xc420276000, 0x99, 0x100)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/tools/filetools.go:232 +0x1fe
github.com/git-lfs/git-lfs/tools.(*fastWalker).Walk.func1(0xc42091e200, 0x10, 0x10)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/tools/filetools.go:273 +0x9c
github.com/git-lfs/git-lfs/tools.(*fastWalker).walk(0xc4201d0240, 0xc42091e200, 0x10, 0x10, 0xc4209e2960)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/tools/filetools.go:287 +0x64
github.com/git-lfs/git-lfs/tools.(*fastWalker).Walk(0xc4201d0240, 0x0, 0xc4201cad80, 0x21, 0xd4d1c0, 0xc4207d04e0, 0xc420276000, 0x99, 0x100)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/tools/filetools.go:271 +0x387
github.com/git-lfs/git-lfs/tools.(*fastWalker).Walk.func1(0xc4207c0700, 0x64, 0x64)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/tools/filetools.go:273 +0x9c
github.com/git-lfs/git-lfs/tools.(*fastWalker).walk.func1(0xc4204eca80, 0xc4207c0700, 0x64, 0x64, 0xc4201d0240)
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/tools/filetools.go:294 +0x44
created by github.com/git-lfs/git-lfs/tools.(*fastWalker).walk
    /var/tmp/portage/dev-vcs/git-lfs-2.3.4/work/git-lfs-2.3.4/src/github.com/git-lfs/git-lfs/tools/filetools.go:293 +0xe0
13:37:16.777542 run-command.c:44        trace: run_command: running exit handler for pid 26030
```
The crashes are random.  Sometimes it doesn't crash at all.  Sometimes it crashes quickly.  Sometimes it crashes slowly.  When it does crash, the stack trace is always the same.

Here's the output of `git lfs env`:

```
git-lfs/2.3.4 (GitHub; linux amd64; go 1.9.2)
git version 2.13.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=
LocalReferenceDir=
TempDir=/tmp/git-lfs
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

If I keep the smudge enabled then it doesn't crash.  Unfortunately, the smudge needs to be disabled because that's how Jenkins clones repositories with large files.  The "git-client" Jenkins plugin performs the following steps to clone a git repository with LFS:

1. Clone the repository with the smudge filter disabled. See https://github.com/jenkinsci/git-client-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java#L2264.
2. Run `git lfs pull` to download large files associated with the checked out commit.  See https://github.com/jenkinsci/git-client-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java#L2298

So far, I am not able to reproduce this issue with Git LFS 2.2.1 in the same environment.

**Comment by creste** [comment]
Downgrading from git-lfs 2.3.4 to 2.2.1 solved the problem on some servers but not all.

After more research, I discovered that this was caused by https://github.com/golang/go/issues/20427.  Upgrading go from 1.9.2 to 1.9.3 fixed the problem for me.

**Comment by ttaylorr** [comment]
> After more research, I discovered that this was caused by golang/go#20427. Upgrading go from 1.9.2 to 1.9.3 fixed the problem for me.

Wow! Great find. I will make sure that the next release of Git LFS is built on a stable version of Go that does not cause this memory corruption.

**Comment by marcan** [comment]
@creste I'm curious, are you on Gentoo Hardened or similar? If there are other triggers other than the exact set of circumstances I described (-fstack-check kernel builds that happen to use a compiler/config combination that adds a stack probe to vDSO code) I'd like to know.

**Comment by creste** [comment]
@marcan - Yes, the affected servers were using Gentoo Hardened with -fstack-check.  We've been running go 1.9.3 for several months now with no problems.  Previously, we were seeing memory corruption once every day or so on go 1.9.2.
