### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference when pulling large object

### ISSUE THREAD

**Issue by jeffreydwalter** [git-lfs/git-lfs#2879]
`go version go1.8 linux/386`
`git-lfs/2.3.4 (GitHub; linux 386; go 1.8; git 6f503b2)`

Built by cloning the git-lfs repo and running the following commands:
```
git clone https://github.com/github/git-lfs.git
cd git-lfs
./script/bootstrap
```

I'm getting the following error pulling large files via Bamboo's Git LFS feature:
```
Fetching 'refs/heads/somebranch' from 'ssh://git@git.server.com/blah/repo.git'. Will try to do a shallow fetch.
Warning: Permanently added '[127.0.0.1]:34441' (RSA) to the list of known hosts.
fetch: Fetching reference refs/heads/somebranch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804965c]

goroutine 1 [running]:
sync/atomic.AddUint64(0x18dfd2ec, 0x7061358, 0x0, 0x0, 0x0)
        /usr/local/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/git-lfs/git-lfs/tq.(*Meter).Add(0x18dfd2d0, 0x7061358, 0x0)
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/tq/meter.go:114 +0x7a
github.com/git-lfs/git-lfs/commands.readyAndMissingPointers(0x189d9b40, 0x6, 0x8, 0x18a3a3c0, 0x189d8000, 0x1891a068, 0x0, 0x0, 0x0, 0x0, ...)
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:351 +0x398
github.com/git-lfs/git-lfs/commands.fetchAndReportToChan(0x189d9b40, 0x6, 0x8, 0x18a3a3c0, 0x0, 0x8)
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:271 +0x50
github.com/git-lfs/git-lfs/commands.fetchRef(0x18a08070, 0x28, 0x18a3a3c0, 0x1)
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:142 +0x79
github.com/git-lfs/git-lfs/commands.fetchCommand(0x18972820, 0x189c9040, 0x2, 0x2)
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/commands/command_fetch.go:87 +0x208
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0x18972820, 0x189c8f60, 0x2, 0x2, 0x18972820, 0x189c8f60)
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0xf8
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0x18972270, 0x18943f94, 0x1)
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x278
github.com/git-lfs/git-lfs/commands.Run()
        /home/build/git-lfs/src/github.com/git-lfs/git-lfs/commands/run.go:71 +0x194
main.main()
        /home/build/git-lfs/git-lfs.go:35 +0xf8
```

**Comment by jeffreydwalter** [comment]
FWIW, I installed go 1.10 and built git-lfs in the same manner and get the exact same error. I also built git-lfs on 64-bit Ubuntu and do NOT get this error.

**Comment by jeffreydwalter** [comment]
Seems like this might be related https://github.com/TheThingsNetwork/ttn/issues/548

**Comment by jeffreydwalter** [comment]
My hunch is that the issue is that you don't have the int64 members in this struct at the top of the struct.
https://github.com/git-lfs/git-lfs/blob/d1cd726b79fca1951e235e8d85f3626934adfafd/tq/meter.go#L21-L39

**Comment by jeffreydwalter** [comment]
Just confirmed that moving the stuff at the top of the struct to the bottom fixes things. Someone obviously didn't read the comment in that struct. 😃 I'll submit a PR shortly.

**Comment by ttaylorr** [comment]
(From my comment in https://github.com/git-lfs/git-lfs/pull/2880#issuecomment-368704027): 

> 2. In a future pull request, we should (a) fix this in other structures, and (b) enable 32-bit builds on supported CI services.

**Comment by ttaylorr** [comment]
Follow up in: https://github.com/git-lfs/git-lfs/pull/2883.
