### ISSUE TITLE
SIGSEGV with `git lfs ls-files -- --all`

### ISSUE THREAD

**Issue by xerus** [git-lfs/git-lfs#2930]
Hi, I wanted to show tracked files on all branches, so I tried `git lfs ls-files -- --all`
Although it may not be a valid command/parameters, it should not crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7fd356]

goroutine 1 [running]:
github.com/git-lfs/git-lfs/commands.lsFilesCommand.func1(0x0, 0xb0ed60, 0xc4201462a0)
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/command_ls_files.go:49 +0x616
github.com/git-lfs/git-lfs/lfs.runScanTree(0xc4201285e0, 0x7ffe1d7500eb, 0x5, 0xc42012ee40, 0x0, 0x0)
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/lfs/gitscanner_tree.go:40 +0x150
github.com/git-lfs/git-lfs/lfs.(*GitScanner).ScanTree(0xc420120580, 0x7ffe1d7500eb, 0x5, 0x0, 0x0)
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/lfs/gitscanner.go:147 +0xaa
github.com/git-lfs/git-lfs/commands.lsFilesCommand(0xc420118ea0, 0xc4200dde80, 0x1, 0x2)
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/command_ls_files.go:103 +0x314
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).execute(0xc420118ea0, 0xc4200ddd00, 0x2, 0x2, 0xc420118ea0, 0xc4200ddd00)
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:477 +0x166
github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200ead00, 0xc420043f10, 0x1)
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/vendor/github.com/spf13/cobra/command.go:551 +0x32b
github.com/git-lfs/git-lfs/commands.Run()
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/commands/run.go:71 +0x1e0
main.main()
	/Users/ttaylorr/go/src/github.com/git-lfs/git-lfs/git-lfs.go:35 +0x111
```
Version: `git-lfs/2.4.0 (GitHub; linux amd64; go 1.8.3; git 1a98fa5c)`

**Comment by ttaylorr** [comment]
Hi @xerus, this looks like a bug to me -- thanks for pointing it out! I went ahead and fixed this in: https://github.com/git-lfs/git-lfs/pull/2932, which I have queued for the next release.

**Comment by xerus** [comment]
Cool, thanks! I can confirm that it's fixed.

Although it's a bit misleading to get a help message for a git command (not for git-lfs ls-files) as the error message.
