### ISSUE TITLE
panic: runtime error: index out of range 9.4 KB/s

### ISSUE THREAD

**Issue by novalagung** [git-lfs/git-lfs#2956]
I got this error when trying to push my revision to github. when this error happen my internet connection was pretty unstable. After trying few times the push success. 

```
$ git push origin master

panic: runtime error: index out of range 9.4 KB/s                                                                                     

goroutine 60 [running]:
github.com/git-lfs/git-lfs/tools/humanize.FormatByteRate(0xfffffffffffffd17, 0x3b9aca00, 0x6, 0x14ddc25)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tools/humanize/humanize.go:160 +0x35c
github.com/git-lfs/git-lfs/tq.(*Meter).str(0xc42012e1b0, 0x150a460, 0xc42056d7a0)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tq/meter.go:242 +0x13e
github.com/git-lfs/git-lfs/tq.(*Meter).update(0xc42012e1b0, 0xd00)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tq/meter.go:219 +0x48
github.com/git-lfs/git-lfs/tq.(*Meter).TransferBytes(0xc42012e1b0, 0x14de7e0, 0x6, 0xc4203f20e9, 0x10, 0xd6e, 0x71b8358, 0xd6e)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tq/meter.go:168 +0x205
github.com/git-lfs/git-lfs/tq.(*TransferQueue).ensureAdapterBegun.func1(0xc4203f20e9, 0x10, 0x71b8358, 0xd6e, 0xd6e, 0x106d310, 0xc42052c114)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tq/transfer_queue.go:731 +0x8b
github.com/git-lfs/git-lfs/tq.(*basicUploadAdapter).DoTransfer.func1(0x71b8358, 0xd6e, 0xd6e, 0xd6e, 0xd6e)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tq/basic_upload.go:81 +0x64
github.com/git-lfs/git-lfs/tools.(*BodyWithCallback).Read(0xc4201b0f90, 0xc420583292, 0xd6e, 0xd6e, 0xc420034f58, 0xc420034f00, 0xc4201b0fd8)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tools/copycallback.go:38 +0x11d
github.com/git-lfs/git-lfs/tq.(*startCallbackReader).Read(0xc42046a480, 0xc420583292, 0xd6e, 0xd6e, 0x1467340, 0x1d5e570, 0x14e06d8)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/tq/basic_upload.go:151 +0x5e
github.com/git-lfs/git-lfs/lfsapi.tracedRead(0x1d5e570, 0xc42046a480, 0xc420583292, 0xd6e, 0xd6e, 0x1543c80, 0xc42000e020, 0x0, 0xc42056db88, 0x12ad2fb, ...)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/lfsapi/verbose.go:115 +0x70
github.com/git-lfs/git-lfs/lfsapi.(*tracedRequest).Read(0xc4201b1170, 0xc420583292, 0xd6e, 0xd6e, 0x12ad2fb, 0x1, 0x1)
    /private/tmp/git-lfs-20180303-1365-bn2fvu/git-lfs-2.4.0/src/github.com/git-lfs/git-lfs/lfsapi/verbose.go:51 +0xa6
net/http.transferBodyReader.Read(0xc4201f6a00, 0xc420583292, 0xd6e, 0xd6e, 0x100f04d, 0xc420010000, 0x1461bc0)
    /usr/local/Cellar/go/1.10/libexec/src/net/http/transfer.go:60 +0x56
io.(*LimitedReader).Read(0xc42044aca0, 0xc420583292, 0xd6e, 0xd6e, 0xc420272380, 0xc4201fdc50, 0x10eab6d)
    /usr/local/Cellar/go/1.10/libexec/src/io/io.go:446 +0x63
bufio.(*Writer).ReadFrom(0xc42013ac00, 0x15437e0, 0xc42044aca0, 0x1dd9220, 0xc42013ac00, 0x1)
    /usr/local/Cellar/go/1.10/libexec/src/bufio/bufio.go:703 +0xcd
io.copyBuffer(0x1543120, 0xc42013ac00, 0x15437e0, 0xc42044aca0, 0x0, 0x0, 0x0, 0x147ac20, 0xc4203eb201, 0xc42044aca0)
    /usr/local/Cellar/go/1.10/libexec/src/io/io.go:386 +0x31a
io.Copy(0x1543120, 0xc42013ac00, 0x15437e0, 0xc42044aca0, 0xc420583290, 0x14dda5a, 0x2)
    /usr/local/Cellar/go/1.10/libexec/src/io/io.go:362 +0x5a
net/http.(*transferWriter).WriteBody(0xc4201f6a00, 0x1543120, 0xc42013ac00, 0x2, 0x2)
    /usr/local/Cellar/go/1.10/libexec/src/net/http/transfer.go:337 +0x5fa
net/http.(*Request).write(0xc420526200, 0x1543120, 0xc42013ac00, 0x0, 0xc4201fdc50, 0x0, 0x0, 0x0)
    /usr/local/Cellar/go/1.10/libexec/src/net/http/request.go:622 +0x6b2
net/http.(*persistConn).writeLoop(0xc4205246c0)
    /usr/local/Cellar/go/1.10/libexec/src/net/http/transport.go:1825 +0x1ea
created by net/http.(*Transport).dialConn
    /usr/local/Cellar/go/1.10/libexec/src/net/http/transport.go:1238 +0x97f
error: failed to push some refs to 'git@github.com:...'
```

**Comment by ttaylorr** [comment]
Hi @novalagung, thanks for opening this. I know that there is one bug that we were tracking about a month ago which was the result of a `panic()` following a misbehaving server. That was fixed in https://github.com/git-lfs/git-lfs/pull/2902.

Could you give that build a shot and let me know if you are still experiencing issues? If so, can you attach a run of this with `GIT_TRACE=1` in your environment (making sure to remove any sensitive details, like authentication tokens?)

Thanks in advance -- we'll definitely get this sorted out.

**Comment by meenanoon0024** [comment]
.

**Comment by meenanoon0024** [comment]
.
