### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by lyda** [git-lfs/git-lfs#3370]
This is being run on a bare repo. Prior to running I ran `git repack --max-pack-size=1g -a -d` to split the 19G pack file into a bunch of 1G pack files.

```
# git lfs --version
git-lfs/2.6.0 (GitHub; linux amd64; go 1.11.1; git 93702d75)
```

```
migrate: Rewriting commits:  61% (5518/8977)                                    
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x91ce54, 0x16)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc14c000000, 0x4000000, 0xd006b8)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0xce73e0, 0x4000000, 0x0, 0xc000b57e30)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0xce73e0, 0xdd, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0xce73e0, 0xdd, 0xd006c8, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0xce73e0, 0xdd, 0x100, 0xa29650)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0xce73e0, 0xdd, 0xc000010100, 0x424b00)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x1ba000, 0x450001, 0xc14bf16000)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:311 fp=0xc0bef0f328 sp=0xc0bef0f320 pc=0x4552b0
runtime.mallocgc(0x1ba000, 0x8cfa80, 0x8f901, 0x8f930)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:913 +0x896 fp=0xc0bef0f3c8 sp=0xc0bef0f328 pc=0x40be16
runtime.newarray(0x8cfa80, 0x2200, 0x8f6020)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:1048 +0x6a fp=0xc0bef0f3f8 sp=0xc0bef0f3c8 pc=0x40c1ea
runtime.makeBucketArray(0x886660, 0xc0f6678c0d, 0x0, 0x90000, 0x867dc0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/map.go:355 +0x184 fp=0xc0bef0f430 sp=0xc0bef0f3f8 pc=0x40d0b4
runtime.makemap(0x886660, 0x8f93, 0xc0f6678c30, 0xc14bf16000)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/map.go:321 +0xec fp=0xc0bef0f478 sp=0xc0bef0f430 pc=0x40ce1c
github.com/git-lfs/git-lfs/tools.NewOrderedSetWithCapacity(...)
	/Users/bk2204/checkouts/git-lfs/tools/ordered_set.go:23
github.com/git-lfs/git-lfs/tools.(*OrderedSet).Union(0xc14bc3b0c0, 0xc00020f6a0, 0xc1334da460)
	/Users/bk2204/checkouts/git-lfs/tools/ordered_set.go:97 +0xae fp=0xc0bef0f520 sp=0xc0bef0f478 pc=0x53cade
github.com/git-lfs/git-lfs/commands.migrateImportCommand.func3(0x914756, 0x1, 0xc14bc3b080, 0x0, 0x0, 0x914756)
	/Users/bk2204/checkouts/git-lfs/commands/command_migrate_import.go:227 +0xe5 fp=0xc0bef0f598 sp=0xc0bef0f520 pc=0x8181b5
github.com/git-lfs/git-lfs/git/githistory.(*Rewriter).rewriteTree(0xc000153b30, 0xc000390000, 0x14, 0x30, 0xc149ed1530, 0x14, 0x30, 0x0, 0x0, 0xc00020f6e0, ...)
	/Users/bk2204/checkouts/git-lfs/git/githistory/rewriter.go:411 +0xd6a fp=0xc0bef0f750 sp=0xc0bef0f598 pc=0x7e1aca
github.com/git-lfs/git-lfs/git/githistory.(*Rewriter).Rewrite(0xc000153b30, 0xc0001cd560, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bk2204/checkouts/git-lfs/git/githistory/rewriter.go:244 +0x603 fp=0xc0bef0f9f0 sp=0xc0bef0f750 pc=0x7e0323
github.com/git-lfs/git-lfs/commands.migrate(0xc0001680a0, 0x0, 0x5, 0xc000153b30, 0xc00005e200, 0xc0000afc90)
	/Users/bk2204/checkouts/git-lfs/commands/command_migrate.go:72 +0x83 fp=0xc0bef0fa40 sp=0xc0bef0f9f0 pc=0x7f0803
github.com/git-lfs/git-lfs/commands.migrateImportCommand(0xc000091a00, 0xc0001680a0, 0x0, 0x5)
	/Users/bk2204/checkouts/git-lfs/commands/command_migrate_import.go:135 +0x105d fp=0xc0bef0fd00 sp=0xc0bef0fa40 pc=0x7f4f6d
github.com/spf13/cobra.(*Command).execute(0xc000091a00, 0xc000168000, 0x5, 0x5, 0xc000091a00, 0xc000168000)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:477 +0x177 fp=0xc0bef0fd90 sp=0xc0bef0fd00 pc=0x7b2597
github.com/spf13/cobra.(*Command).Execute(0xc00014c000, 0xc0000aff18, 0x1)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:551 +0x109 fp=0xc0bef0fea8 sp=0xc0bef0fd90 pc=0x7b2989
github.com/git-lfs/git-lfs/commands.Run(0x10)
	/Users/bk2204/checkouts/git-lfs/commands/run.go:77 +0x1ef fp=0xc0bef0ff30 sp=0xc0bef0fea8 pc=0x8104ef
main.main()
	/Users/bk2204/checkouts/git-lfs/git-lfs.go:35 +0xec fp=0xc0bef0ff98 sp=0xc0bef0ff30 pc=0x81b8fc
runtime.main()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/proc.go:201 +0x207 fp=0xc0bef0ffe0 sp=0xc0bef0ff98 pc=0x42c217
runtime.goexit()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0bef0ffe8 sp=0xc0bef0ffe0 pc=0x457211

goroutine 18 [syscall, 7 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/Cellar/go/1.11.1/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/Cellar/go/1.11.1/libexec/src/os/signal/signal_unix.go:29 +0x41

goroutine 4 [chan receive, 7 minutes]:
main.main.func1(0xc00006c300, 0xc000020070)
	/Users/bk2204/checkouts/git-lfs/git-lfs.go:23 +0x76
created by main.main
	/Users/bk2204/checkouts/git-lfs/git-lfs.go:21 +0xe7

goroutine 20 [chan receive]:
github.com/git-lfs/git-lfs/tasklog.(*Logger).logTask(0xc00005e200, 0x9aaf20, 0xc00012ec90)
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:216 +0xf1
github.com/git-lfs/git-lfs/tasklog.(*Logger).consume.func1(0xc00005e200)
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:147 +0x5f
created by github.com/git-lfs/git-lfs/tasklog.(*Logger).consume
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:143 +0x57

goroutine 7 [chan receive, 7 minutes]:
github.com/git-lfs/git-lfs/tasklog.(*Logger).consume(0xc00005e200)
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:166 +0x2dd
created by github.com/git-lfs/git-lfs/tasklog.NewLogger
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:63 +0x12a
```

**Comment by ttaylorr** [comment]
Hi @lyda, thanks for opening this most interesting issue. I am sorry that you are having trouble, and we will certainly work to figure out what's going on so that we can get this resolved.

I'm curious what sort of memory is being held on to to make this operation so memory-costly that it exceeds the available memory allocated to the process. Here are a few baseline questions that I'd be curious of your answers to in order to get us started:

1. How much memory is the process eligible to use? Running `git lfs migrate` most likely requires a ~100MiB or so of space, so if you're underneath this threshold, the problem lies there.

2. Is this example reproducible? Does your invocation of `git lfs migrate` _consistently_ cause it to fail in the above manner? If so, can you cause the issue to happen on a source build of Git LFS (after cloning the repository, run `make`, and use `bin/git-lfs`). If so too, can you share a copy of your repository, or create a new one that causes the issue to happen?

3. Can you attach a memory profiler to the process to see what parts of the code are allocating the most? A discussion on how to do this is here: https://github.com/git-lfs/git-lfs/issues/2439.

**Comment by lyda** [comment]
Thanks for the reply.

1) This is on a machine with 8g of RAM. I added swap on one run to bump it up to 16g and it got to around 12g and I stopped it as it was crawling by that point.

2) I used a release build from here. But yes, I can build locally and run that. I can't share the repo sadly. I'll try the memory profiler trick.

3) Yes, I can look into doing that.

There's no huge pressure. I'm using BFG for now to do the conversion. There are lots of things that need to be done to this repo and related infrastructure to do the migration but for the lfs part BFG seems to do the trick. Still the repo seems to exercise a bug in lfs migrate and fixing it might help make it work better, so I'll get the memory profiler going to see if we can track it down.

Oh, one unusual thing is the repo is being converted with Subgit in a one-shot process. I do note that it makes a .gitattributes entry at the base of the repo for every file.

**Comment by ttaylorr** [comment]
> Oh, one unusual thing is the repo is being converted with Subgit in a one-shot process. I do note that it makes a .gitattributes entry at the base of the repo for every file.

Hmm, I'm not sure what Subgit is, but in any event we should not be creating one `.gitattributes` _per file_. Is it reproducible with vanilla Git?

**Comment by lyda** [comment]
Er, sorry, I wasn't clear. [Subgit](https://subgit.com/) creates a single .gitattributes file at the base tree of every commit detailing information on each file. I was wondering if git-lfs might find that difficult to deal with.

And sorry for not following up on your request. I don't live in the States but I am from there so prepping for Thanksgiving dinner. So the next two weeks are too busy. But once I clear those I'll dig into this.

**Comment by x-yang11** [comment]
Hi，I have run into the same problem. When I ran `git lfs migrate import ...`, I see the memory usage is 1.86 G when my mac-mini has 16G RAM.

below is the log.

```
migrate: Sorting commits: ..., done
runtime: out of memory: cannot allocate 1215938560-byte block (1874362368 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x420370, 0xd)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:608 +0x64
runtime.largeAlloc(0x4879a320, 0x40101, 0x84d000)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:1021 +0x101
runtime.mallocgc.func1()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:914 +0x33
runtime.systemstack(0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_386.s:396 +0x47
runtime.mstart()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_386.s:357 fp=0x11d5d690 sp=0x11d5d68c pc=0x4c180
runtime.mallocgc(0x4879a320, 0x3ae980, 0x4b1501, 0x11c7fa30)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/malloc.go:913 +0x65e fp=0x11d5d6e4 sp=0x11d5d690 pc=0xad3e
runtime.makeslice(0x3ae980, 0x4879a320, 0x4879a320, 0x11d5d71c, 0xc, 0x11d5d718)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/slice.go:70 +0x53 fp=0x11d5d6f8 sp=0x11d5d6e4 pc=0x3a403
runtime.makeslice64(0x3ae980, 0x4879a320, 0x0, 0x4879a320, 0x0, 0x0, 0x47, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/slice.go:85 +0x49 fp=0x11d5d714 sp=0x11d5d6f8 pc=0x3a4b9
github.com/git-lfs/gitobj/pack.(*ChainBase).Unpack(0x126cc500, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/git-lfs/gitobj@v1.0.0/pack/chain_base.go:39 +0xf0 fp=0x11d5d74c sp=0x11d5d714 pc=0x11ad90
github.com/git-lfs/gitobj/pack.(*Object).Unpack(0x11c7f9f0, 0xaf76, 0xa3b9, 0xffffffff, 0x1, 0x4acc05)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/git-lfs/gitobj@v1.0.0/pack/object.go:20 +0x20 fp=0x11d5d768 sp=0x11d5d74c pc=0x11cbe0
github.com/git-lfs/gitobj/pack.(*delayedObjectReader).Read(0x11c7fa00, 0x19aa3000, 0x1000, 0x1000, 0x47, 0x47, 0x1)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/git-lfs/gitobj@v1.0.0/pack/delayed_object.go:21 +0x82 fp=0x11d5d7d0 sp=0x11d5d768 pc=0x11b6b2
io/ioutil.(*nopCloser).Read(0x11c0e1b0, 0x19aa3000, 0x1000, 0x1000, 0xa3b9, 0x3fffffff, 0x0)
	<autogenerated>:1 +0x3f fp=0x11d5d7f0 sp=0x11d5d7d0 pc=0xe14af
bufio.(*Reader).fill(0x11c17e00)
	/usr/local/Cellar/go/1.11.1/libexec/src/bufio/bufio.go:100 +0xe9 fp=0x11d5d818 sp=0x11d5d7f0 pc=0xca549
bufio.(*Reader).ReadSlice(0x11c17e00, 0x420, 0xc, 0xc, 0x18, 0x11c7fa20, 0x856ebc)
	/usr/local/Cellar/go/1.11.1/libexec/src/bufio/bufio.go:341 +0x26 fp=0x11d5d838 sp=0x11d5d818 pc=0xcb026
bufio.(*Reader).ReadBytes(0x11c17e00, 0xbc4020, 0x1000, 0x11c17e00, 0x11c17e00, 0x11c7fa10, 0x11c0e1b0)
	/usr/local/Cellar/go/1.11.1/libexec/src/bufio/bufio.go:419 +0x42 fp=0x11d5d8a4 sp=0x11d5d838 pc=0xcb3b2
bufio.(*Reader).ReadString(0x11c17e00, 0x11c0e120, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/bufio/bufio.go:459 +0x24 fp=0x11d5d8cc sp=0x11d5d8a4 pc=0xcb6c4
github.com/git-lfs/gitobj.(*ObjectReader).Header(0x11c7fa10, 0xbc4030, 0x11c7fa00, 0x11c7fa10, 0x0, 0x0)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/git-lfs/gitobj@v1.0.0/object_reader.go:103 +0x31 fp=0x11d5d90c sp=0x11d5d8cc pc=0x125501
github.com/git-lfs/gitobj.(*ObjectDatabase).decode(0x11d2e640, 0x11c7fa10, 0x4b4060, 0x126cc4c0, 0x11c7fa10, 0x0)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/git-lfs/gitobj@v1.0.0/object_db.go:310 +0x1f fp=0x11d5d93c sp=0x11d5d90c pc=0x124e8f
github.com/git-lfs/gitobj.(*ObjectDatabase).openDecode(0x11d2e640, 0x2a7e3520, 0x14, 0x14, 0x4b4060, 0x126cc4c0, 0xc0, 0x182fcc40)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/git-lfs/gitobj@v1.0.0/object_db.go:298 +0x6f fp=0x11d5d95c sp=0x11d5d93c pc=0x124e4f
github.com/git-lfs/gitobj.(*ObjectDatabase).Blob(0x11d2e640, 0x2a7e3520, 0x14, 0x14, 0x5, 0x25d5d9ac, 0x26168)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/git-lfs/gitobj@v1.0.0/object_db.go:116 +0x5b fp=0x11d5d984 sp=0x11d5d95c pc=0x123fdb
github.com/git-lfs/git-lfs/git/githistory.(*Rewriter).rewriteBlob(0x11d2e860, 0x11e2e930, 0x14, 0x30, 0x2a7e3520, 0x14, 0x14, 0x186a04e0, 0x15, 0x11d43710, ...)
	/Users/bk2204/checkouts/git-lfs/git/githistory/rewriter.go:453 +0x3a fp=0x11d5d9d8 sp=0x11d5d984 pc=0x3281ba
github.com/git-lfs/git-lfs/git/githistory.(*Rewriter).rewriteTree(0x11d2e860, 0x11e2e930, 0x14, 0x30, 0x2a7e3080, 0x14, 0x14, 0x123200b0, 0x7, 0x11d43710, ...)
	/Users/bk2204/checkouts/git-lfs/git/githistory/rewriter.go:393 +0x97f fp=0x11d5dab0 sp=0x11d5d9d8 pc=0x327d2f
github.com/git-lfs/git-lfs/git/githistory.(*Rewriter).rewriteTree(0x11d2e860, 0x11e2e930, 0x14, 0x30, 0x12f0a0f0, 0x14, 0x30, 0x0, 0x0, 0x11d43710, ...)
	/Users/bk2204/checkouts/git-lfs/git/githistory/rewriter.go:395 +0x8ea fp=0x11d5db88 sp=0x11d5dab0 pc=0x327c9a
github.com/git-lfs/git-lfs/git/githistory.(*Rewriter).Rewrite(0x11d2e860, 0x11d8e330, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/bk2204/checkouts/git-lfs/git/githistory/rewriter.go:244 +0x545 fp=0x11d5dcd8 sp=0x11d5db88 pc=0x326b05
github.com/git-lfs/git-lfs/commands.migrate(0x11c7eae0, 0x0, 0x2, 0x11d2e860, 0x11cf9b60, 0x11d5de60)
	/Users/bk2204/checkouts/git-lfs/commands/command_migrate.go:72 +0x64 fp=0x11d5dcfc sp=0x11d5dcd8 pc=0x333ec4
github.com/git-lfs/git-lfs/commands.migrateImportCommand(0x11c82410, 0x11c7eae0, 0x0, 0x2)
	/Users/bk2204/checkouts/git-lfs/commands/command_migrate_import.go:135 +0xd2c fp=0x11d5de94 sp=0x11d5dcfc pc=0x33774c
github.com/spf13/cobra.(*Command).execute(0x11c82410, 0x11c7e9f0, 0x2, 0x2, 0x11c82410, 0x11c7e9f0)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:477 +0x101 fp=0x11d5ded8 sp=0x11d5de94 pc=0x301501
github.com/spf13/cobra.(*Command).Execute(0x11c825b0, 0x11c8ef98, 0x1)
	/Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:551 +0x231 fp=0x11d5df60 sp=0x11d5ded8 pc=0x301961
github.com/git-lfs/git-lfs/commands.Run(0x8)
	/Users/bk2204/checkouts/git-lfs/commands/run.go:77 +0x1a9 fp=0x11d5dfa0 sp=0x11d5df60 pc=0x34dd59
main.main()
	/Users/bk2204/checkouts/git-lfs/git-lfs.go:35 +0xd6 fp=0x11d5dfd0 sp=0x11d5dfa0 pc=0x3570e6
runtime.main()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/proc.go:201 +0x1ee fp=0x11d5dff0 sp=0x11d5dfd0 pc=0x2805e
runtime.goexit()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_386.s:1324 +0x1 fp=0x11d5dff4 sp=0x11d5dff0 pc=0x4d8f1

goroutine 18 [syscall, 6 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/sigqueue.go:139 +0x128
os/signal.loop()
	/usr/local/Cellar/go/1.11.1/libexec/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
	/usr/local/Cellar/go/1.11.1/libexec/src/os/signal/signal_unix.go:29 +0x31

goroutine 20 [chan receive, 6 minutes]:
main.main.func1(0x11c60400, 0x11c6d060)
	/Users/bk2204/checkouts/git-lfs/git-lfs.go:23 +0x46
created by main.main
	/Users/bk2204/checkouts/git-lfs/git-lfs.go:21 +0xd1

goroutine 25 [chan receive, 6 minutes]:
github.com/git-lfs/git-lfs/tasklog.(*Logger).consume(0x11cf9b60)
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:166 +0x234
created by github.com/git-lfs/git-lfs/tasklog.NewLogger
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:63 +0xfe

goroutine 33 [chan receive]:
github.com/git-lfs/git-lfs/tasklog.(*Logger).logTask(0x11cf9b60, 0x4b3280, 0x11c48060)
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:216 +0xbc
github.com/git-lfs/git-lfs/tasklog.(*Logger).consume.func1(0x11cf9b60)
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:147 +0x58
created by github.com/git-lfs/git-lfs/tasklog.(*Logger).consume
	/Users/bk2204/checkouts/git-lfs/tasklog/log.go:143 +0x3b
```

Result of `git lfs env` is here.

```
git-lfs/2.6.0 (GitHub; darwin 386; go 1.11.1; git 93702d75)
git version 2.17.2 (Apple Git-113)

Endpoint=https://g.***.com/A***e/A***e.git/info/lfs (auth=none)
  SSH=git@g.***.com:A***e/A***e
Endpoint (new)=https://g.***.com/h***4/A***e-NEW.git/info/lfs (auth=none)
  SSH=git@g.***.com:h***4/A***e-NEW
LocalWorkingDir=/Users/y***o/lfs_migrate/A***e
LocalGitDir=/Users/y***o/lfs_migrate/A***e/.git
LocalGitStorageDir=/Users/y***o/lfs_migrate/A***e/.git
LocalMediaDir=/Users/y***o/lfs_migrate/A***e/.git/lfs/objects
LocalReferenceDirs=
TempDir=/Users/y***o/lfs_migrate/A***e/.git/lfs/tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/Users/y***o/lfs_migrate/A***e/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Comment by bk2204** [comment]
I think the problem that you're seeing here is that you're using a 32-bit binary, which is going to be limited to 2 GiB of address space.  If your Mac supports it, I'd recommend switching to a 64-bit binary instead, which should let you make better use of the memory on your system.
