### ISSUE TITLE
git lfs status crashes with "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by pavelsalamon** [git-lfs/git-lfs#3395]
git lfs status crashes in my clone:
```
$ git lfs status
panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7fc098]
goroutine 1 [running]:
github.com/git-lfs/git-lfs/lfs.(*PointerScanner).Close(...)
        C:/Users/brian m. carlson/checkouts/git-lfs/lfs/gitscanner_catfilebatch.go:114
github.com/git-lfs/git-lfs/commands.statusCommand(0xc000154ea0, 0xcdc938, 0x0, 0x0)
        C:/Users/brian m. carlson/checkouts/git-lfs/commands/command_status.go:36 +0x848
github.com/spf13/cobra.(*Command).execute(0xc000154ea0, 0xcdc938, 0x0, 0x0, 0xc000154ea0, 0xcdc938)
        C:/Users/brian m. carlson/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:477 +0x17e
github.com/spf13/cobra.(*Command).Execute(0xc0000a3a00, 0xc00008bf18, 0x1)
        C:/Users/brian m. carlson/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:551 +0x120
github.com/git-lfs/git-lfs/commands.Run(0x10)
        C:/Users/brian m. carlson/checkouts/git-lfs/commands/run.go:77 +0x1f6
main.main()
        C:/Users/brian m. carlson/checkouts/git-lfs/git-lfs.go:35 +0xf3
```

My lfs env:
```
$ git lfs env
git-lfs/2.6.0 (GitHub; windows amd64; go 1.11.1; git 93702d75)
git version 2.19.2.windows.1

Endpoint=https://xxxx@bitbucket.org/xxxx.git/info/lfs (auth=basic)
LocalWorkingDir=xxxxxx
LocalGitDir=xxxxxx
LocalGitStorageDir=xxxxxx
LocalMediaDir=xxxxxx
LocalReferenceDirs=
TempDir=xxxxxxx
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=xxxxxx
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

The clone that this happens in was created with older git/lfs versions:
```
git-lfs/2.0.2 (GitHub; windows amd64; go 1.8; git 85e2aec4)
git version 2.12.2.windows.2
```

My working tree is completely clean (no tracked/untracked/unpushed changes).

After the version upgrade I noticed the git lfs status failing.
On a new clone the command runs successfully, so this is probably related to upgrading git and lfs versions?

**Comment by bk2204** [comment]
Hey, thanks for writing in, and sorry to hear you're having trouble.

I think this is fixed with 7dae495, which we'll likely include in a 2.6.1 release relatively soon.  Could you test with the latest `master` branch and see if your issue is fixed?

**Comment by pavelsalamon** [comment]
Thanks for the quick reply.

I've tried with latest master. At first, this was the output:
```
$ git lfs status
open C:\Users\xxxxx\git\xxxx\.git\objects\pack\pack-28599e76ee72d0789a5857fa15fffd599754e789.idx: The system cannot find the file specified.
```

**Comment by bk2204** [comment]
Also, it would be useful to know if that file does indeed exist on disk, or if it is genuinely missing.

**Comment by pavelsalamon** [comment]
All my clones were created by default `git lfs clone` with no additional flags.

The pack file is genuinely missing on disk when the error references it (before running `git gc`).

**Comment by bk2204** [comment]
I think we can probably handle this situation a bit better.  If you're legitimately missing the index, then I think git-lfs/gitobj#8 should improve this for you.

We do have plans for including the commit I mentioned above in 2.6.1 (you can see the PR in #3339), although not for git-lfs/gitobj#8 at the moment.  We can always do a 2.6.2 release in the future if we want to include that, though.

**Comment by pavelsalamon** [comment]
Ok, looks like git-lfs/gitobj#8 will solve my missing index problem. Until it's released, I can run `git gc` to workaround the issue. Thanks.

**Comment by ElectricRCAircraftGuy** [comment]
The following worked for me on Linux Ubuntu 18.04:

```
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
```
See: https://packagecloud.io/github/git-lfs/install

Then:
```
sudo apt update
sudo apt install git-lfs
```

That updated my `git-lfs` version from one in 2017 to the latest one in Mar 2021, as shown at the very bottom of the man pages shown by `man git-lfs`.

Now, `sudo apt install git-lfs` tells me:

> git-lfs is already the newest version (2.13.3).

**Comment by chrisd8088** [comment]
The crash reported in this issue was fixed with commit 7dae495442111ea09000ee7ebeb7f9c61ba3d66c in PR #3383, which was included in Git LFS version 2.6.1.

The change to handle a missing Git index from commit git-lfs/gitobj@561ed224a6bd39232d902ad8023c0ebe44fbf6c5 in PR git-lfs/gitobj#8 is included in versions 1.2.0 and above of the `git-lfs/gitobj` package.  Git LFS upgraded to v1.3.0 of that package in commit 094b8c3d4154aab418302207d30f17be6a9dfdf5 of PR #3685, which was included in Git LFS version 2.8.0.

As both problems discussed in this issue have been addressed, I'm going to close this issue.
