### ISSUE TITLE
SIGSEGV: segmentation violation code=0x1 

### ISSUE THREAD

**Issue by alibaba4** [git-lfs/git-lfs#3431]
```
git lfs env
git-lfs/2.6.0 (GitHub; linux amd64; go 1.11.1; git 93702d75)
git version 2.5.0

```
```
git lfs ls-files
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x76c2d3]

goroutine 1 [running]:
github.com/git-lfs/git-lfs/lfs.scanIndex(0xc000152620, 0xc000196700, 0x28, 0xc00014b9b0, 0x0, 0x0)
        /Users/bk2204/checkouts/git-lfs/lfs/gitscanner_index.go:100 +0x423
github.com/git-lfs/git-lfs/lfs.(*GitScanner).ScanIndex(0xc00017da00, 0xc000196700, 0x28, 0x0, 0xcfed08, 0x0)
        /Users/bk2204/checkouts/git-lfs/lfs/gitscanner.go:191 +0xb3
github.com/git-lfs/git-lfs/commands.lsFilesCommand(0xc0001781a0, 0xcfed08, 0x0, 0x0)
        /Users/bk2204/checkouts/git-lfs/commands/command_ls_files.go:109 +0x2f7
github.com/spf13/cobra.(*Command).execute(0xc0001781a0, 0xcfed08, 0x0, 0x0, 0xc0001781a0, 0xcfed08)
        /Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:477 +0x177
github.com/spf13/cobra.(*Command).Execute(0xc000142000, 0xc000053f18, 0x1)
        /Users/bk2204/checkouts/go/pkg/mod/github.com/spf13/cobra@v0.0.0-20150809222549-c55cdf33856a/command.go:551 +0x109
github.com/git-lfs/git-lfs/commands.Run(0x10)
        /Users/bk2204/checkouts/git-lfs/commands/run.go:77 +0x1ef
main.main()
        /Users/bk2204/checkouts/git-lfs/git-lfs.go:35 +0xec

```

**Comment by alibaba4** [comment]
Hi Brian,

Sorry foe late reply. Unfortunately, this is not publicly available repo. The issue  is some what sporadic, I have no notice a way to reproduce it.
I see this, though:

```
git lfs status
On branch pr824

Git LFS objects to be committed:


Git LFS objects not staged for commit:

       ******.zip (?: <missing> -> File: db97a2b)
       ******.zip (?: <missing> -> File: 3a9175e)

```

**Comment by bk2204** [comment]
It sounds like you may be missing some LFS objects. Does `git lfs fsck` pass? If not, can you try `git lfs fetch --all` to see if that fetches the missing objects?

**Comment by alibaba4** [comment]
Unfortunately both commands seems to block forever and never finish.

**Comment by bk2204** [comment]
Can you try using Git LFS 2.6.1? 2.6.0 had a known bug where it could hang in some circumstances, and I'm wondering if this is one of those situations.

Also, it might be useful to check with `git fsck` as well to make sure you're not missing any regular Git objects as well.
