### ISSUE TITLE
Intermittent `Authentication required` error

### ISSUE THREAD

**Issue by alex-sf** [git-lfs/git-lfs#4041]
**Describe the bug**

There are few things to know about what we are doing:

1) We have a prepush hook that runs `git lfs pre-push` 
2) In our Ci (CircleCi) we are running a promotion job that removes that hook before it creates tags and does a fast forward push from one branch to another. 

This second step is intermittently failing (The push will work about half the time) in the CI with the following error:

```
ERROR: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'git@github.com:MGMResorts/********.git'

/root/********/build/utils/run.ts:26
    throw new Error('an error occurred');
          ^
Error: an error occurred
    at Object.run (/root/********/build/utils/run.ts:26:11)
    at Object.<anonymous> (/root/********/build/bin/promote.ts:89:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/root/********/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/root/********/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**

Removing the LFS pre-push would not cause a verification block since we are not running any LFS commands.

**Comment by bk2204** [comment]
Hey,

This error comes from GitHub, and it's often seen when there's a permissions problem because lock verification is the first step to pushing.  I don't know what your authentication looks like in this case, but that's what the message means.

In your case, removing the hook is not a good idea because Git LFS will reinstall missing hooks if they are absent, although it will not modify custom hooks.  That might happen in some case if it gets invoked by Git because of a worktree change.  If you want to run a push without the hook for whatever reason, you can use the `--no-verify` flag.  If there are other things in the hook you want to do, but not the `git lfs pre-push` command, you can condition the `git lfs pre-push` on an environment variable, and then set that environment variable before running your push.

I suspect if you do one of those, then you won't invoke Git LFS, which seems to be what you're intending.

**Comment by julian-sf** [comment]
@bk2204 Thanks for the reply.  I work with @alex-sf and we absolutely love Git LFS!

In regards to your comment, we're not actively avoiding invocation of LFS, it's just the solution we were using to get around the intermittent authentication errors with GitHub.

> Git LFS will reinstall missing hooks if they are absent

Are you saying that when `git-lfs` is installed it will (sometimes?) create a `pre-push` hook if one doesn't exist on the invocation of a command like `git push`?  I was under the impression that was only done on `git lfs install/update`?  We are running this in a one-off container that is destroyed immediately after this process is done, we assumed deletion of the hook would:
- be the most effective way to bypass this error all together
- and would be "safe", as we were basically ending the container after the `git push origin ... --tags` command is run

Our git command is guaranteed to be a fast-forward push, due to the way our process works.  Since we were deleting the hook, I guess the only way this error COULD be happening is if the hook is inadvertently recreated right?

Regardless, I think the `--no-verify` option would be a good way forward for us if that allows us to bypass the lock authentication checks altogether.  I guess my big question (for GitHub probably) is: why do we have to do this at all?  Is there something wrong with the GitHub authentication process?  It seems weird that the same CI job with the same ssh key (and thus user/permissions) would fail only sometimes.  I understand you can't control the GitHub authentication process, I'm just merely curious at this point.

Anyway, thank you for your suggestions and such a great tool!

**Comment by bk2204** [comment]
> > Git LFS will reinstall missing hooks if they are absent
> 
> Are you saying that when `git-lfs` is installed it will (sometimes?) create a `pre-push` hook if one doesn't exist on the invocation of a command like `git push`? I was under the impression that was only done on `git lfs install/update`?

When Git LFS is invoked by Git, it will usually install hooks (including the `pre-push` hook) unless they've been changed.  This is so that when you do a clone of a repository using Git LFS, the hooks get installed automatically,  Any custom hooks are preserved.

Now, normally, Git LFS is not invoked on push unless there's a pre-push hook.  However, having said that, if your CI job is doing something like modifying a working tree file and the index is updated under the hood (or you're invoking `git reset --hard`), you can end up with Git LFS invoked and the hook installed.

> Our git command is guaranteed to be a fast-forward push, due to the way our process works. Since we were deleting the hook, I guess the only way this error COULD be happening is if the hook is inadvertently recreated right?

I suspect that's the case.

> Regardless, I think the `--no-verify` option would be a good way forward for us if that allows us to bypass the lock authentication checks altogether. I guess my big question (for GitHub probably) is: why do we have to do this at all? Is there something wrong with the GitHub authentication process? It seems weird that the same CI job with the same ssh key (and thus user/permissions) would fail only sometimes. I understand you can't control the GitHub authentication process, I'm just merely curious at this point.

I don't know why this behavior is only showing up periodically for you.  If it's a thing you're seeing, please definitely do reach out to the GitHub support team, because if there's a problem, we'd like to fix it, and they have access to look at logs and figure out what's going on, and if necessary, open an issue with the appropriate team.

One thing you may also want to do from a debugging perspective is to set the `lfs.<url>.locksverify` setting to `false` and see if that fixes your problem.  If so, it'll be clearer where the problem is (the lock server) instead of another authentication process.

**Comment by julian-sf** [comment]
@bk2204 Thanks for the reply.  Sorry I’ve been slow to respond.  I will check tomorrow in the AM and see if we can get the failures to stop if we disable lock verification.

I’m also going to add some logging around the command that fails and check to see if a `pre-push` hook is getting recreated.  Either way I’ll let you know how it goes.

Thanks again!

**Comment by michaellee8** [comment]
I somehow got this problem passed by providing a personal access token hardcoded to the git remote url, without removing the git hooks or switching the config. idk if this will help.
