### ISSUE TITLE
stderr: error: external filter 'git-lfs filter-process --skip' failed

### ISSUE THREAD

**Issue by arturoar3nas** [git-lfs/git-lfs#4149]
Hello,

I'm working with Jenkins docker in docker and git plugin. My private repository have git lfs and i set the below config:

```
GIT_LFS_SKIP_SMUDGE=1
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip"
```
  
then i get the next error: 

```
hudson.plugins.git.GitException: Command "git checkout -f 4e1a685bf99f14fbdcfc24040093c476e75d593e" returned status code 128:
stdout: 
stderr: error: external filter 'git-lfs filter-process --skip' failed
error: git-lfs filter-process --skip died of signal 15
fatal: mpi/rsrc/test_videos/_video1.avi: smudge filter lfs failed
```
Why this is happened? I appreciate any help! 

Thanks!

**Comment by chrisd8088** [comment]
Hey, I'm sorry you're having trouble!  Would you be able to provide some additional information to help us understand what might be going wrong?

If you could paste the output of `git lfs env` and `git config -l` (removing any personal information, like your email address), that would be helpful.

And then if you could try your Git LFS command again but with the environment variables `GIT_TRACE=1 GIT_TRACE_PACKET=1 GIT_TRANSFER_TRACE=1 GIT_CURL_VERBOSE=1` set, and paste all the debug output from that, it might give us a lead on what's happening.

**Comment by arturoar3nas** [comment]
Hey Chris, 

Thanks for your response ,  I'm run the below script in Jenkins:

```

pipeline {
    agent
    {
        docker
        {
            image 'myowndockerimage'
            args '-u root:1000 -v $HOME/workspace/project:/project'
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    environment {
        GIT_TRACE_PACKET=1
        GIT_TRACE=1 
        GIT_CURL_VERBOSE=1
   }
   stages {

        stage("Setup-Env") {
            steps {
                sh "dnf install -y doxygen git-lfs"
            }
        }
        stage('Checkout') {
            steps {
                sh "git lfs env"
                git credentialsId: '71eb7781-2c04-4547-9c85-5edf03f2fd9d', url: 'https://myrepository.git', branch: 'master'
            }
        }
   }
```

i changed a bit the settings and this is the output: 

```
+ git lfs env
```
```
02:53:32.029473 git.c:670               trace: exec: git-lfs env
02:53:32.029522 run-command.c:643       trace: run_command: git-lfs env
trace git-lfs: exec: git 'version'
git-lfs/2.11.0 (Fedora 30; linux amd64; go 1.12.17)
git version 2.21.3

trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
trace git-lfs: Error loading current ref: Git can't resolve ref: "HEAD"
trace git-lfs: exec: git 'config' '-l'
Endpoint=https://myrepository.git/info/lfs (auth=basic)
LocalWorkingDir=/var/jenkins_home/workspace/project
LocalGitDir=/var/jenkins_home/workspace/project/.git
LocalGitStorageDir=/var/jenkins_home/workspace/project/.git
LocalMediaDir=/var/jenkins_home/workspace/project/.git/lfs/objects
LocalReferenceDirs=
TempDir=/var/jenkins_home/workspace/project/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/var/jenkins_home/workspace/project/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_CURL_VERBOSE=1
GIT_EXEC_PATH=/usr/libexec/git-core
GIT_TRACE=1
GIT_TRACE_PACKET=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
trace git-lfs: filepathfilter: accepting "tmp"
```

```
[Pipeline] git
```
```
using credential 71eb7781-2c04-4547-9c85-5edf03f2fd9d
Warning: JENKINS-30600: special launcher org.jenkinsci.plugins.docker.workflow.WithContainerStep$Decorator$1@30f6a52b; decorates hudson.Launcher$LocalLauncher@3e315d45 will be ignored (a typical symptom is the Git executable not being run inside a designated container)
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url http://myrepository.git # timeout=10
Fetching upstream changes from https://myrepository.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --force --progress -- https://myrepository.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 3cc734cfb6c089931d8f2d2130d7336ede00ee13 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 3cc734cfb6c089931d8f2d2130d7336ede00ee13 # timeout=10

$ docker stop --time=1 cbdd84e86ea8243763a420add004050f9599a9ba73d049a144c42dbe55750954
$ docker rm -f cbdd84e86ea8243763a420add004050f9599a9ba73d049a144c42dbe55750954

```
```
Error:
```
```
hudson.plugins.git.GitException: Command "git checkout -f 3cc734cfb6c089931d8f2d2130d7336ede00ee13" returned status code 128:
stdout: 
stderr: Downloading project/test/videos-xenics/video_01.avi (183 MB)
Error downloading object: project/test/videos-xenics/video_01.avi (8cde8bf): Smudge error: Error downloading project/test/videos-xenics/video_01.avi (8cde8bfede1daafeac5d40c96f79f45f871ce1ee9dee2d820be6225c00478595): batch response: Authorization error: https://myrepository.git/info/lfs/objects/batch
Check that you have proper access to the repository

Errors logged to /var/jenkins_home/workspace/project/.git/lfs/logs/20200604T025400.78196491.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process -- %f' failed
fatal: project/test/videos-xenics/video_01.avi: smudge filter lfs failed

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1100(CliGitAPIImpl.java:81)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2725)
Caused: hudson.plugins.git.GitException: Could not checkout master with start point 3cc734cfb6c089931d8f2d2130d7336ede00ee13
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2765)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1217)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:93)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

I can't to identify what is happening

**Comment by arturoar3nas** [comment]
Hello Chris,

Pardon me for reply to late, i can solved my problem whit the below script

```
stage('Checkout') {
    steps {
        script{
            try{
                sh "git lfs env"
                git credentialsId: 'ssh_key_id', url: 'ssh://git@url.git', branch: 'master'
        
            }
            catch(e)
            {
                echo e.getMessage()
                echo "ctest error: something bad is happening here!"
            }
            finally
            {
            withEnv(['GIT_SSH_COMMAND=ssh -o StrictHostKeyChecking=no']) {
                    sshagent(credentials: ['ssh_key_id'])  {
                        sh "git remote set-url origin ssh://git@url.git"
                        sh "git lfs fetch origin --all"
                        sh '''#!/bin/bash -ex
                            git config --global filter.lfs.smudge "git-lfs smudge -- %f"
                            git config --global filter.lfs.required true
                            git config --global filter.lfs.clean "git-lfs clean -- %f"
                        '''
                        sh "git lfs checkout"
                        sh "rm -rf ticpp_ip_libs/"
                        sh "git submodule sync"
                        sh "git submodule init"
                        sh "git submodule update"
                        sh "git rev-list --max-parents=0 HEAD"
                    }
                }
            }
        }
    }
}
```

Thanks a lot for support me I really appreciate that!!

Best Regards

**Comment by chrisd8088** [comment]
I'm delighted to hear it's working for you!
