### ISSUE TITLE
Git LFS crash when push with empty object id

### ISSUE THREAD

**Issue by sluongng** [git-lfs/git-lfs#4303]
**Describe the bug**
When run `git lfs push --oid ''` git lfs would crash with a stack trace

**To Reproduce**
1. Try passing an empty object ID into git LFS push

**Expected behavior**
Git LFS gracefully exit, prompting user that an empty object IDs was not allowed.

Better yet if we can just filter out all of the empty object IDs among the provided objects.

**System environment**
Centos7

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
```
# Omit as its not very relevant
git-lfs/2.12.0 (GitHub; linux amd64; go 1.15.2)
git version 2.27.0.284.g2915947361
```

**Additional context**
Any other relevant context about the problem here.

```
> git lfs push --object-id origin ''
panic: runtime error: slice bounds out of range [:2] with length 0

goroutine 1 [running]:
github.com/git-lfs/git-lfs/fs.(*Filesystem).localObjectDir(0xc00024e000, 0x7ffc63dc01ca, 0x0, 0xc000254030, 0x7fb94c5a9048)
        /builddir/build/BUILD/git-lfs-2.12.0/fs/fs.go:123 +0xef
github.com/git-lfs/git-lfs/fs.(*Filesystem).ObjectPath(0xc00024e000, 0x7ffc63dc01ca, 0x0, 0xc000254030, 0x6, 0xc00021ab70, 0xc000220f10)
        /builddir/build/BUILD/git-lfs-2.12.0/fs/fs.go:68 +0x5a
github.com/git-lfs/git-lfs/lfs.(*GitFilter).ObjectPath(...)
        /builddir/build/BUILD/git-lfs-2.12.0/lfs/gitfilter.go:21
github.com/git-lfs/git-lfs/commands.uploadsWithObjectIDs(0xc00026c0b0, 0xc000098fa0, 0x1, 0x2)
        /builddir/build/BUILD/git-lfs-2.12.0/commands/command_push.go:80 +0xce
github.com/git-lfs/git-lfs/commands.pushCommand(0xc0000db180, 0xc000098f90, 0x2, 0x3)
        /builddir/build/BUILD/git-lfs-2.12.0/commands/command_push.go:52 +0xf2
github.com/spf13/cobra.(*Command).execute(0xc0000db180, 0xc000098f60, 0x3, 0x3, 0xc0000db180, 0xc000098f60)
        /builddir/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000092000, 0xc000139f08, 0x1, 0x1)
        /builddir/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
github.com/git-lfs/git-lfs/commands.Run(0x10)
        /builddir/build/BUILD/git-lfs-2.12.0/commands/run.go:103 +0x318
main.main()
        /builddir/build/BUILD/git-lfs-2.12.0/git-lfs.go:33 +0xec
```

**Comment by sluongng** [comment]
Not too sure about a fix, perhaps something like this

```
diff --git a/commands/command_push.go b/commands/command_push.go
index 48de5b98..53e81bdf 100644
--- a/commands/command_push.go
+++ b/commands/command_push.go
@@ -77,6 +77,11 @@ func uploadsBetweenRefAndRemote(ctx *uploadContext, refnames []string) {
 func uploadsWithObjectIDs(ctx *uploadContext, oids []string) {
        pointers := make([]*lfs.WrappedPointer, len(oids))
        for i, oid := range oids {
+               if oid == "" {
+                       Print("Skipping empty object-id")
+                       continue
+               }
+
                mp, err := ctx.gitfilter.ObjectPath(oid)
                if err != nil {
                        ExitWithError(errors.Wrap(err, "Unable to find local media path:"))
```

would do the job

**Comment by sluongng** [comment]
Let me know if the patch above worth a PR 🤔

**Comment by bk2204** [comment]
Hey,

I agree that panicking in this case is undesirable.  I think the change needs to be a little different so that we can accomodate other invalid values as well, so I'll push up a PR.

**Comment by sluongng** [comment]
Thanks Brian 👍
