### ISSUE TITLE
sporadic git checkout failure during lfs filtering content stage

### ISSUE THREAD

**Issue by acorn-sdk** [git-lfs/git-lfs#4382]
**Describe the issue**
Sporadic git checkout failure during lfs filtering content stage

**System environment**
OS - Ubuntu18.04
Run git checkout directly on the host server
```
git config -l
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
lfs.concurrenttransfers=100
push.default=simple
user.name=svcaccount
user.email=svcaccount@xxx.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
submodule.recurse=true
```

**Output of `git lfs env`**
```
git lfs env
git-lfs/2.11.0 (GitHub; linux amd64; go 1.13.4)
git version 2.27.0

LocalWorkingDir=
LocalGitDir=
LocalGitStorageDir=
LocalMediaDir=lfs/objects
LocalReferenceDirs=
TempDir=lfs/tmp
ConcurrentTransfers=100
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file
UploadTransfers=basic,lfs-standalone-file
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```
**Additional context**
The detailed error message is attached below. It happens very sporadically but need help with understanding the error here.
```
stdout: 
stderr: Filtering content:  13% (291/2230), 300.29 MiB | 587.94 MiB/s
Filtering content:  14% (313/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  15% (335/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  16% (357/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  17% (380/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  18% (402/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  19% (424/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  20% (446/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  21% (469/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  22% (491/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  23% (513/2230), 607.93 MiB | 594.00 MiB/s
Filtering content:  23% (530/2230), 889.32 MiB | 377.55 MiB/s
Filtering content:  23% (533/2230), 1.27 GiB | 264.42 MiB/s  
Filtering content:  23% (534/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  24% (536/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  25% (558/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  26% (580/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  27% (603/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  28% (625/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  29% (647/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  30% (669/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  31% (692/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  32% (714/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  33% (736/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  34% (759/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  35% (781/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  36% (803/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  37% (826/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  38% (848/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  39% (870/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  40% (892/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  41% (915/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  42% (937/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  42% (953/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  43% (959/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  44% (982/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  45% (1004/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  46% (1026/2230), 1.60 GiB | 292.14 MiB/s
Filtering content:  47% (1049/2230), 1.60 GiB | 292.14 MiB/s
fatal error: gentraceback callback cannot be used with non-zero skip

runtime stack:
runtime.throw(0xaa51ec, 0x37)
	/usr/local/go/src/runtime/panic.go:774 +0x72
runtime.gentraceback(0xffffffffffffffff, 0xffffffffffffffff, 0x0, 0xc000784c00, 0x0, 0x0, 0x7fffffff, 0x7facd37fdb68, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:100 +0x1a30
runtime.scanstack(0xc000784c00, 0xc000035270)
	/usr/local/go/src/runtime/mgcmark.go:711 +0x15d
runtime.scang(0xc000784c00, 0xc000035270)
	/usr/local/go/src/runtime/proc.go:886 +0x1e3
runtime.markroot.func1()
	/usr/local/go/src/runtime/mgcmark.go:221 +0x6d
runtime.markroot(0xc000035270, 0x7fac000000c5)
	/usr/local/go/src/runtime/mgcmark.go:202 +0x2f3
runtime.gcDrain(0xc000035270, 0x2)
	/usr/local/go/src/runtime/mgcmark.go:915 +0x110
runtime.gcBgMarkWorker.func2()
	/usr/local/go/src/runtime/mgc.go:1932 +0x120
runtime.systemstack(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1146

goroutine 531 [GC worker (idle)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0005c4760 sp=0xc0005c4758 pc=0x45a980
runtime.gcBgMarkWorker(0xc000034000)
	/usr/local/go/src/runtime/mgc.go:1900 +0x1bd fp=0xc0005c47d8 sp=0xc0005c4760 pc=0x41dc1d
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0005c47e0 sp=0xc0005c47d8 pc=0x45ca51
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1794 +0x77

goroutine 1 [chan receive]:
github.com/git-lfs/git-lfs/commands.readAvailable(0xc00027c240, 0x64, 0x14, 0x1, 0xc0004a62c8)
	/tmp/docker_run/src/git-lfs/amd64/commands/command_filter_process.go:334 +0x1b5
github.com/git-lfs/git-lfs/commands.filterCommand(0xc0001bb900, 0xf92598, 0x0, 0x0)
	/tmp/docker_run/src/git-lfs/amd64/commands/command_filter_process.go:150 +0x129e
github.com/spf13/cobra.(*Command).execute(0xc0001bb900, 0xf92598, 0x0, 0x0, 0xc0001bb900, 0xf92598)
	/tmp/docker_run/src/git-lfs/amd64/vendor/github.com/spf13/cobra/command.go:766 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ba000, 0xc00011dee0, 0x1, 0x1)
	/tmp/docker_run/src/git-lfs/amd64/vendor/github.com/spf13/cobra/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/tmp/docker_run/src/git-lfs/amd64/vendor/github.com/spf13/cobra/command.go:800
github.com/git-lfs/git-lfs/commands.Run(0x10)
	/tmp/docker_run/src/git-lfs/amd64/commands/run.go:103 +0x33b
main.main()
	/tmp/docker_run/src/git-lfs/amd64/git-lfs.go:33 +0xec

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 34 [chan receive]:
main.main.func1(0xc0001281e0, 0xc0001ae000)
	/tmp/docker_run/src/git-lfs/amd64/git-lfs.go:21 +0x6d
created by main.main
	/tmp/docker_run/src/git-lfs/amd64/git-lfs.go:19 +0xe7
.....
.....
.....
goroutine 2580 [select]:
golang.org/x/net/http2.(*ClientConn).roundTrip(0xc000499c80, 0xc000136500, 0x0, 0x0, 0x0, 0x0)
	/tmp/docker_run/src/git-lfs/amd64/vendor/golang.org/x/net/http2/transport.go:1084 +0x9a0
golang.org/x/net/http2.(*Transport).RoundTripOpt(0xc0000b6fc0, 0xc000136500, 0xc000817000, 0x73c0f5, 0x0, 0xc0005be240)
	/tmp/docker_run/src/git-lfs/amd64/vendor/golang.org/x/net/http2/transport.go:447 +0x172
golang.org/x/net/http2.(*Transport).RoundTrip(...)
	/tmp/docker_run/src/git-lfs/amd64/vendor/golang.org/x/net/http2/transport.go:408
golang.org/x/net/http2.noDialH2RoundTripper.RoundTrip(0xc0000b6fc0, 0xc000136500, 0xc00092de60, 0x5, 0xc0005be2c8)
	/tmp/docker_run/src/git-lfs/amd64/vendor/golang.org/x/net/http2/transport.go:2589 +0x3e
net/http.(*Transport).roundTrip(0xc000120640, 0xc000136500, 0x410e3e, 0xb62c18, 0x0)
	/usr/local/go/src/net/http/transport.go:485 +0xdc1
net/http.(*Transport).RoundTrip(0xc000120640, 0xc000136500, 0xc000120640, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000136500, 0xb74f80, 0xc000120640, 0x0, 0x0, 0x0, 0xc0003be028, 0xc000817580, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:250 +0x443
net/http.(*Client).send(0xc0005b46c0, 0xc000136500, 0x0, 0x0, 0x0, 0xc0003be028, 0x0, 0x1, 0x47903c)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc0005b46c0, 0xc000136500, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:509
github.com/git-lfs/git-lfs/lfshttp.(*Client).DoWithRedirect(0xc000282320, 0xc0005b46c0, 0xc000136500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x6, 0xc000817880, ...)
	/tmp/docker_run/src/git-lfs/amd64/lfshttp/client.go:293 +0x143
github.com/git-lfs/git-lfs/lfsapi.(*Client).doWithCreds(0xc000278340, 0xc000136500, 0xb806e0, 0xf92300, 0x0, 0x0, 0x0, 0xa877f7, 0x4, 0xc000b570e0, ...)
	/tmp/docker_run/src/git-lfs/amd64/lfsapi/auth.go:103 +0x21d
github.com/git-lfs/git-lfs/lfsapi.(*Client).doWithAuth(0xc000278340, 0xc00026a201, 0x6, 0xa877f7, 0x4, 0xc000b570e0, 0x4d, 0xc000136500, 0x0, 0x0, ...)
	/tmp/docker_run/src/git-lfs/amd64/lfsapi/auth.go:67 +0x1af
github.com/git-lfs/git-lfs/lfsapi.(*Client).DoWithAuthNoRetry(...)
	/tmp/docker_run/src/git-lfs/amd64/lfsapi/auth.go:46
github.com/git-lfs/git-lfs/tq.(*adapterBase).doHTTP(0xc00039a000, 0xc001385680, 0xc000136500, 0x0, 0x0, 0x0)
	/tmp/docker_run/src/git-lfs/amd64/tq/adapterbase.go:231 +0x118
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).makeRequest(0xc0017609e8, 0xc001385680, 0xc000136500, 0x11, 0xc000136500, 0x0)
	/tmp/docker_run/src/git-lfs/amd64/tq/basic_download.go:285 +0x46
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).download(0xc0017609e8, 0xc001385680, 0xc00136ecc0, 0x0, 0xc00093a150, 0x0, 0xb85060, 0xc000e2a000, 0x0, 0x0)
	/tmp/docker_run/src/git-lfs/amd64/tq/basic_download.go:139 +0x139
github.com/git-lfs/git-lfs/tq.(*basicDownloadAdapter).DoTransfer(0xc0017609e8, 0x0, 0x0, 0xc001385680, 0xc00136ecc0, 0x0, 0x0, 0x0)
	/tmp/docker_run/src/git-lfs/amd64/tq/basic_download.go:101 +0x404
github.com/git-lfs/git-lfs/tq.(*adapterBase).worker(0xc00039a000, 0x44, 0x0, 0x0)
	/tmp/docker_run/src/git-lfs/amd64/tq/adapterbase.go:182 +0x504
created by github.com/git-lfs/git-lfs/tq.(*adapterBase).Begin
	/tmp/docker_run/src/git-lfs/amd64/tq/adapterbase.go:95 +0x255
fatal: the remote end hung up unexpectedly
````

Any suggestion will be helpful! Thank you!
Jason

**Comment by bk2204** [comment]
Hey,

This looks like an internal Go error.  Could you try the latest version of Git LFS, preferably built with a newer Go?  We have artifacts from CI if you want to try those, and we also have packages that should be suitable for Ubuntu 18.04.

**Comment by acorn-sdk** [comment]
Thank you Brain! 
Let me try git lfs version 2.13.2 and go major version 1.14.

Thanks,
Jason
