### ISSUE TITLE
jsii/superchain generating qemu: uncaught target signal 6 (aborted) error when run on new Mac (arm64)

### ISSUE THREAD

**Issue by biffgaut** [git-lfs/git-lfs#4560]
**Describe the bug**
We're building a CDK construct library on the jsii/superchain:latest docker container. When we run `yarn run jsii-pacmak` across our repo we see this error in the first folder run against. [This article](https://github.com/docker/for-mac/issues/5148) suggests the problem is running an amd64 image on an arm64 host.

**To Reproduce**
1. Clone our repo on a new Mac (arm64)
2. cd aws-solutions-constructs
3. start the container using `docker run --rm --net=host -it -v $PWD:$PWD -w $PWD jsii/superchain`
4. run `./deployment/build-patterns.sh`

The entire library needs to be built before it runs the packaging command. Depending upon how many system resources you have devoted to docker it can take 30 minutes to a couple hours (I have 6 CPUs assigned to docker to get 30 minutes).

Error:
```
packaging...
lerna notice cli v3.22.1
lerna info Executing command in 44 packages: "yarn run jsii-pacmak"
@aws-solutions-constructs/core: yarn run v1.22.5
@aws-solutions-constructs/core: $ jsii-pacmak
@aws-solutions-constructs/core: [xmldom warning]        attribute "arguments" missed value!! "arguments" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "that" missed value!! "that" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "are" missed value!! "are" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "passed" missed value!! "passed" instead!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "arguments" missed value!! "arguments" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "that" missed value!! "that" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "are" missed value!! "are" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "passed" missed value!! "passed" instead!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "arguments" missed value!! "arguments" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "that" missed value!! "that" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "are" missed value!! "are" instead2!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [xmldom warning]        attribute "passed" missed value!! "passed" instead!! 
@aws-solutions-constructs/core: @#[line:1,col:1]
@aws-solutions-constructs/core: [jsii-pacmak] [WARN] Exception occurred, not cleaning up 
@aws-solutions-constructs/core: [jsii-pacmak] [WARN] dotnet failed
@aws-solutions-constructs/core: Error: Command (dotnet new sln -n JsiiBuild) failed with signal SIGABRT:
@aws-solutions-constructs/core: #STDERR> qemu: uncaught target signal 6 (Aborted) - core dumped
@aws-solutions-constructs/core: #STDERR> 
@aws-solutions-constructs/core: #STDOUT> 
@aws-solutions-constructs/core:     at ChildProcess.child.once (/Users/cmicky/VSCode/aws-solutions-constructs/source/node_modules/jsii-pacmak/lib/util.js:120:27)
@aws-solutions-constructs/core:     at Object.onceWrapper (events.js:286:20)
@aws-solutions-constructs/core:     at ChildProcess.emit (events.js:198:13)
@aws-solutions-constructs/core:     at maybeClose (internal/child_process.js:982:16)
@aws-solutions-constructs/core:     at Socket.stream.socket.on (internal/child_process.js:389:11)
@aws-solutions-constructs/core:     at Socket.emit (events.js:198:13)
@aws-solutions-constructs/core:     at Pipe._handle.close (net.js:607:12)
@aws-solutions-constructs/core: error Command failed with exit code 1.
@aws-solutions-constructs/core: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run jsii-pacmak exited 1 in '@aws-solutions-constructs/core'
real    1m29.191s
user    1m11.732s
sys     0m6.121s```

**Expected behavior**
A clear and concise description of what you expected to happen.

**System environment**
MacBook Pro (13-inch M1, 2020)
Chip: Apple M1
Memory 16GB
macOS Big Sur 11.3.1

**Output of `git lfs env`**
The output of running `git lfs env` as a code block.
```
bash-4.2# git lfs env
git: 'lfs' is not a git command. See 'git --help'.
```


**Additional context**
Any other relevant context about the problem here.

<!--
Please note: if you're receiving a message from the server side (including a
`batch response` message), please contact your Git hosting provider.  This
repository is for the Git LFS client only; problems with GitHub's server-side
LFS support should be reported to them as described in the `CONTRIBUTING.md`
file.
-->

**Comment by bk2204** [comment]
Hey,

I'm not sure how this relates to Git LFS.  Can you maybe explain that in a little more detail?

**Comment by biffgaut** [comment]
Wow, this was supposed to go on the JSII repo. I must have inadvertently navigated off that page before opening the issue. Sorry, it doesn't belong here at all - I will close.
