### ISSUE TITLE
Client certificates silently ignored if paths specified with "~/"

### ISSUE THREAD

**Issue by PalCla** [git-lfs/git-lfs#5652]
**Describe the bug**
Client certificate is ignored if path is specified with "~/...".

Basically:
```
[http "https://.../"]
       sslCert = ~/trt/sec/keystore_..._cert.pem # working in git, but ignored in git lfs
       sslKey =  ~/trt/sec/keystore_..._key.pem  # working in git, but ignored in git lfs
       sslCert = /home/dev/trt/sec/keystore_..._cert.pem # working in both
       sslKey =  /home/dev/trt/sec/keystore_..._key.pem  # working in both
```

I found these env and set them:
```
GIT_TRACE=1
GIT_TRACE_PACKET=1
GIT_TRACE_PERFORMANCE=1
GIT_TRACE_SETUP=1
GIT_CURL_VERBOSE=1
GIT_TRANSFER_TRACE=1
```
Running "git lfs pull" shows this for about a second:
`Downloading LFS objects:   0% (0/1), 0 B | 0 B/s`
and then this:
```
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
batch response: Client error: https://{url}/{group}/{project_name}.git/info/lfs/objects/batch
Failed to fetch some objects from 'https://{url}/{group}/{project_name}.git/info/lfs'
```

I had this problem for months but never found out why. That's why I disabled git lfs for normal "git pull"
and just tried to find out why it wasn't working from time to time.

Now after using the full path it's working as expected.

Encountered the problem in a docker container, where I wanted to use the same client certificate for the host and the container.
That was the reason, why I was not using a full path, but ~/ instead and this worked for a normal git pull.

**To Reproduce**
1. Set up client certificates with leading "~/".
2. Verify that client certificates are working with git pull
3. Try git lfs pull

**Expected behavior**
git lfs using the client certificate and no error.
A error, if sslCert and/or sslKey is set and can't be loaded instead of silently ignoring it.

**System environment**
Host: manjaro
Docker container: Ubuntu "20.04.3 LTS (Focal Fossa)"

git config -l
```
git-lfs/3.4.1 (GitHub; linux amd64; go 1.21.1)
git version 2.43.0

Endpoint=https://{url}/{group}/{project_name}.git/info/lfs (auth=basic)
LocalWorkingDir=/workspaces/{project_name}
LocalGitDir=/workspaces/{project_name}/.git
LocalGitStorageDir=/workspaces/{project_name}/.git
LocalMediaDir=/workspaces/{project_name}/.git/lfs/objects
LocalReferenceDirs=
TempDir=/workspaces/{project_name}/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/workspaces/{project_name}/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Output of `git lfs env`**
```
git-lfs/3.4.1 (GitHub; linux amd64; go 1.21.1)
git version 2.43.0

Endpoint=https://{url}/{group}/{project_name}.git/info/lfs (auth=basic)
LocalWorkingDir=/workspaces/{project_name}
LocalGitDir=/workspaces/{project_name}/.git
LocalGitStorageDir=/workspaces/{project_name}/.git
LocalMediaDir=/workspaces/{project_name}/.git/lfs/objects
LocalReferenceDirs=
TempDir=/workspaces/{project_name}/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/workspaces/{project_name}/.git/lfs
AccessDownload=basic
AccessUpload=basic
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

**Additional context**

While writing this I created a dummy file "foobar" > \~/dummy_file and used it for cert and key.
Pointing to it with "~/dummy_file" results in git pull:
`fatal: unable to access 'https://{url}/{group}/{project_name}.git/': error reading X.509 key or certificate file`
and in the above error with git lfs pull.
I found this interesting because, when I use the full path I get the same error for git pull:
`fatal: unable to access 'https://{url}/{group}/{project_name}.git/': error reading X.509 key or certificate file`
but for git lfs pull I get:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x82f02d]

goroutine 53 [running]:
crypto/x509.IsEncryptedPEMBlock(...)
	/usr/local/go/src/crypto/x509/pem_decrypt.go:105
github.com/git-lfs/git-lfs/v3/lfshttp.getClientCertForHost(0xc000167f40, {0xc00009c308, 0x13})
	/tmp/docker_run/src/git-lfs/amd64/lfshttp/certs.go:87 +0x34d
github.com/git-lfs/git-lfs/v3/lfshttp.(*Client).Transport(0xc000167f40, 0xc00031c1b0, {0xc00030054c, 0x5})
	/tmp/docker_run/src/git-lfs/amd64/lfshttp/client.go:467 +0x465
github.com/git-lfs/git-lfs/v3/lfshttp.(*Client).HttpClient(0xc000167f40, 0xc00031c1b0, {0xc00030054c, 0x5})
	/tmp/docker_run/src/git-lfs/amd64/lfshttp/client.go:508 +0x1cd
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).doWithCreds(0xc00031a600, 0xc000390b00, {{0xb52de0, 0xc00059ef60}, 0xc00059ee40, 0xc00031cab0, 0xc00059f0b0}, {{0xc00030054c, 0x5}, {0xc0000285f0, ...}}, ...)
	/tmp/docker_run/src/git-lfs/amd64/lfsapi/auth.go:100 +0x1a7
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).doWithAuth(0xc00031a600, {0xc0003003ed, 0x6}, {{0xc00030054c, 0x5}, {0xc0000285f0, 0x45}}, 0xc000390b00, {0x0, 0x0, ...})
	/tmp/docker_run/src/git-lfs/amd64/lfsapi/auth.go:68 +0x1cb
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoWithAuth(0xc00031a600, {0xc0003003ed, 0x6}, {{0xc00030054c, 0x5}, {0xc0000285f0, 0x45}}, 0xc000390b00)
	/tmp/docker_run/src/git-lfs/amd64/lfsapi/auth.go:26 +0x6d
github.com/git-lfs/git-lfs/v3/lfsapi.(*Client).DoAPIRequestWithAuth(0xc00031a600, {0xc0003003ed, 0x6}, 0xc000390b00)
	/tmp/docker_run/src/git-lfs/amd64/lfsapi/auth.go:57 +0x134
github.com/git-lfs/git-lfs/v3/tq.(*tqClient).Batch(0xc0003740c0, {0xc0003003ed, 0x6}, 0xc000511080)
	/tmp/docker_run/src/git-lfs/amd64/tq/api.go:94 +0x3dc
github.com/git-lfs/git-lfs/v3/tq.Batch({0xb56a10, 0xc000133080}, 0x1, {0xc0003003ed, 0x6}, 0x1?, {0xc000134a80, 0x64, 0x64})
	/tmp/docker_run/src/git-lfs/amd64/tq/api.go:45 +0x2b3
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).enqueueAndCollectRetriesFor(0xc00016e500, {0xc0000dd880, 0x64, 0x0?})
	/tmp/docker_run/src/git-lfs/amd64/tq/transfer_queue.go:581 +0x2fe
github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches.func1()
	/tmp/docker_run/src/git-lfs/amd64/tq/transfer_queue.go:470 +0x85
created by github.com/git-lfs/git-lfs/v3/tq.(*TransferQueue).collectBatches in goroutine 43
	/tmp/docker_run/src/git-lfs/amd64/tq/transfer_queue.go:463 +0x29b
```
And that's the reason I think it's getting silently ignored.

**Comment by bk2204** [comment]
Hey,

Thanks for the report.  It does appear that Git expands `~` here and we don't.  I don't think this should be too difficult to fix, but it probably won't make it into the 3.5 release on Wednesday.  Nonetheless, I'll try to take a look pretty soon.

**Comment by bk2204** [comment]
I've got a draft PR in #5657 that should address this.
