### ISSUE TITLE
git lfs status fails on empty repository

### ISSUE THREAD

**Issue by asottile** [git-lfs/git-lfs#913]
### Test script

``` bash
rm -rf bar
mkdir bar
pushd bar
git init .
git lfs install
echo 'oh hi' > a
git lfs track a
git add .
git lfs status
git lfs logs last
popd
```
### Output

```
$ bash -x test2.sh
+ rm -rf bar
+ mkdir bar
+ pushd bar
/tmp/foo/bar /tmp/foo
+ git init .
Initialized empty Git repository in /tmp/foo/bar/.git/
+ git lfs install
Updated pre-push hook.
Git LFS initialized.
+ echo 'oh hi'
+ git lfs track a
Tracking a
+ git add .
+ git lfs status
Could not get the current ref

Errors logged to /tmp/foo/bar/.git/lfs/objects/logs/20151225T101909.261976109.log
Use `git lfs logs last` to view the log.
+ git lfs logs last
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1; git 258acf1)
git version 1.9.1

$ git-lfs status
Could not get the current ref

Git can't resolve ref: "HEAD"
goroutine 1 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f39606e61e8, 0xc8200300d0, 0x7f39606e2028, 0xc82000f4c0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7f39606e2028, 0xc82000f4c0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7f39606e2028, 0xc82000f4c0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f39606e2028, 0xc82000f4c0, 0x9599c0, 0x1d, 0x0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.Panic(0x7f39606e2028, 0xc82000f4c0, 0x9599c0, 0x1d, 0x0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:83 +0x5d
github.com/github/git-lfs/commands.statusCommand(0xb5c120, 0xb85c50, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/commands/command_status.go:24 +0xb8
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).execute(0xb5c120, 0xb85c50, 0x0, 0x0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:477 +0x403
github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra.(*Command).Execute(0xb5cfc0, 0x0, 0x0)
    /Users/rick/go/src/github.com/github/git-lfs/vendor/_nuts/github.com/spf13/cobra/command.go:551 +0x46a
github.com/github/git-lfs/commands.Run()
    /Users/rick/go/src/github.com/github/git-lfs/commands/commands.go:88 +0x23
main.main()
    /Users/rick/go/src/github.com/github/git-lfs/git-lfs.go:34 +0x12e

ENV:
LocalWorkingDir=/tmp/foo/bar
LocalGitDir=/tmp/foo/bar/.git
LocalGitStorageDir=/tmp/foo/bar/.git
LocalMediaDir=/tmp/foo/bar/.git/lfs/objects
TempDir=/tmp/foo/bar/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
+ popd
/tmp/foo
```

**Comment by technoweenie** [comment]
Thanks for the report!

**Comment by jakub-m** [comment]
With 2.1.0 I cannot reproduce it anymore. The actual output is:

```
[...]
+ git add .
+ git lfs status

Git LFS objects to be committed:

	.gitattributes (Git: 9483a3b)
	a (LFS: 5f2977d)

Git LFS objects not staged for commit:


+ git lfs logs last
No logs to show
```

It seems it can be closed now.

**Comment by ttaylorr** [comment]
🎉 !
