### ISSUE TITLE
Cant fetch files tracked by lfs

### ISSUE THREAD

**Issue by ramv-dailymotion** [git-lfs/git-lfs#982]
```
$ git lfs logs last
git-lfs/1.1.0 (GitHub; linux amd64; go 1.5.1)
git version 2.3.5


$ git-lfs pull
Error updating the git index


exit status 128
goroutine 39 [running]:
github.com/github/git-lfs/lfs.Stack(0x0, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/lfs/errors.go:557 +0x80
github.com/github/git-lfs/commands.logPanicToWriter(0x7f8d33ed61e8, 0xc820108150, 0x7f8d33ed6a88, 0xc820108180)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:184 +0xf7f
github.com/github/git-lfs/commands.logPanic(0x7f8d33ed6a88, 0xc820108180, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:148 +0x421
github.com/github/git-lfs/commands.handlePanic(0x7f8d33ed6a88, 0xc820108180, 0x0, 0x0)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:123 +0x4e
github.com/github/git-lfs/commands.LoggedError(0x7f8d33ed6a88, 0xc820108180, 0x95d480, 0x1f, 0xc820067e80, 0x1, 0x1)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/commands.go:73 +0x82
github.com/github/git-lfs/commands.checkoutWithChan(0xc82001e480)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:229 +0xa5c
github.com/github/git-lfs/commands.checkoutFromFetchChan.func1(0xc82001e480, 0xc82013c060)
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:78 +0x21
created by github.com/github/git-lfs/commands.checkoutFromFetchChan
    /tmp/docker_run/git-lfs/obj-x86_64-linux-gnu/src/github.com/github/git-lfs/commands/command_checkout.go:80 +0x439

ENV:
LocalWorkingDir=/data/rviswanadha/data/rc-recommend
LocalGitDir=/home/rviswanadha/data/rc-recommend/.git
LocalGitStorageDir=/home/rviswanadha/data/rc-recommend/.git
LocalMediaDir=/home/rviswanadha/data/rc-recommend/.git/lfs/objects
TempDir=/home/rviswanadha/data/rc-recommend/.git/lfs/tmp
ConcurrentTransfers=3
BatchTransfer=true
```

**Comment by technoweenie** [comment]
Hi, I'm going through and replying to old issues that I've missed. Your git index is corrupt here. I'm not sure what the best course of action is in this scenario, other than http://makandracards.com/makandra/5899-how-to-fix-a-corrupt-git-index. Can you describe how it got into that state?

**Comment by ttaylorr** [comment]
I'm in a similar space as @technoweenie above, but I am going to close this issue out in the meantime, since it has grown quite stale (and hopefully you have recovered your index by now :smile:).
